### ISSUE TITLE
Where to Put the Potency/Clearance Data for this Series

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#1]
The inherited data for this series, and the data we're likely to acquire soon, will consist of whole cell potency _vs_ MRSA and _in vitro_ clearance rates. These are different from the typical data we'll be acquiring for the fragments in Series 1, in the mur ligase project.

Yet we really ought to try to reduce fragmentation and keep data in one place.

Shall we upload the inherited data to the [current OSA spreadsheet](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit?usp=sharing), in a separate tab? Danger: if we use one numbering system for both series (we should), we may become confused as to where we're up to.

Ping @drc007 for opinion, as well as anyone else.

**Comment by drc007** [comment]
We need to have a single numbering system, or if a compound is tested in multiple assays you will end up with multiple identifiers. We need a single registration system, the the spreadsheet is not ideal but at present is the best we have. We should revisit the grant to support creation of a proper registration system now we have a prototype database we can use to demo.

**Comment by drc007** [comment]
@mattodd Main spreadsheet should be used for registration, to get a unique ID, and generate InChiKey etc. Biological results can go in a separate sheet, but using the unique ID molecule identifier as key.

Does this make sense?

**Comment by danaklug** [comment]
@drc007 Yep, I think this is the best system. Does it make sense to add SB-044868 and the ALM-DAI focused array compounds to the spreadsheet now? I'm just thinking maybe it's best to consistently refer to them by OSA numbers from the beginning. Happy to add them if you also think that's a good idea!

**Comment by drc007** [comment]
@danaklug If you are willing to do that it would be great.

**Comment by danaklug** [comment]
@drc007  No problem!

**Comment by danaklug** [comment]
Okay, this is done - I've just filled in SMILES, InCHIKey, name, and MW.

@fidiris @rhanson1046 FYI: All ALM compounds now have OSA IDs.

**Comment by drc007** [comment]
Excellent!!

**Comment by rhanson1046** [comment]
Good to see the launch. Now I just need to get the "feel" of GitHub.
Rob
________________________________

**Comment by fidiris** [comment]
_Just to summarise and close this issue._ 

New compounds will be assigned an **OSA ID** and added to the **master sheet**. Once we get biological data back, this will go in a separate tab using the OSA ID as the molecule identifier. 

Link to the sheet can be found [here](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit#gid=2078630269)
