### ISSUE TITLE
ADME data - Dec 2021

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#104]
As discussed in #102, the below compounds have been sent to NEU for ADME assays (aq. sol., HLM clearance, rat hepatocyte clearance, LogD, PPB). Results will be posted here when they come in.

![image](https://user-images.githubusercontent.com/53487492/143896866-3db3e894-2396-4d46-9152-a3c28f066d7f.png)

**Comment by QSimpson** [comment]
We have existing data for an earlier batch of OSA_987;
MRC5 TC50 (uM) 6.04
PMM TC50 (uM) 32
Aqueous Solubility (uM) 8
HLM CLint (uL/min/mg protein) 137
Rat Hepatocyte CLint (uL/min/10x6 cells) >300
LogD 7.4 3.4

**Comment by edwintse** [comment]
ADME results with colour coding as per issue #80 
![Dec ADME Results](https://user-images.githubusercontent.com/18062981/153396789-894da9a5-8614-41c3-a9d4-a70d3e8cd864.jpeg)

**Comment by mattodd** [comment]
975's not bad. Do we have tox for it? Can't see it.

**Comment by edwintse** [comment]
No, doesn't look like we have any tox for 975

**Comment by lferrins** [comment]
I agree that 975 looks the most promising (I would probably colour code Rat Hepatocyte CLint as green!). I also just emailed you the tox and parasite data for 975 (and a couple of other compounds) and there is no appreciable toxicity in MRC5 or PMM cell lines!

**Comment by mattodd** [comment]
Hi @danielgedder I wonder if we can easily access compounds like 975 (keeping the para-CN) with other substituents on the aromatic rings while maintaining the low logP?

**Comment by danielgedder** [comment]
Hi @mattodd, I've drawn some proposals of compounds that I guess could improve or keep the same LogD as 975; based on the calculated LogD (please, take a look at the figure).
I took a look at the main SAR, and Nitrile has been replaced for chorine and other groups, but maybe we still can work with other replacements like CF3 or Fluorine (can increase a bit the LogD), as well as exchanging the phenyl group for a cyclohexane group (can decrease the LogD). At the second line, adding a Nitrogen atom to the phenyl group can decrease the LogD.
At the bottom, I made some proposals keeping the nitrile group and adding other groups like -CF3, -OMe or –OH. These groups might keep the same LogD.

The proposed compound bearing the 4F-phenyl group and OSA_812 are in this ALK paper: https://pubs.acs.org/doi/pdf/10.1021/jm010493y (this ref. is already cited in the OSA manuscript).

![Calculated log D](https://user-images.githubusercontent.com/88835924/153577475-9f4d6fa9-aaa1-423f-b0e2-1ca0fb94ae4a.jpg)

**Comment by drc007** [comment]
Did we ever make

**Comment by lferrins** [comment]
I was just looking through the SAR summary in [issue 94](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/94) and was scribbling some ideas that I don't think we have tried yet (someone fact check me?). I was aiming to keep the cLogP in the vicinity of 2 (or slightly lower). Obviously, if some of these work (like replacing the pyridine with the pyrimidine) you could imagine different regioisomers. 

I'm not sure that we have ever tried to truncate the bicycle down to the imidazole, though I am not convinced we should go in with the -NH free, or if we should use N-methyl imidazole? Thoughts from the group on that one?

@drc007 I can't figure out which structure you are referring to - can you include an image, please?

![image](https://user-images.githubusercontent.com/65637708/153672001-9bef55a7-4a78-4baf-b5b2-e93c8760a598.png)

**Comment by QSimpson** [comment]
821, 875, 975 and 1018 all have significantly higher microsomal clearance when compared to the hepatocyte clearance. Because of the large discrepancy between the assays doesn't this suggest uptake rate limited metabolism for the hepatocyte assay? They also have a spread of "ideal" LogDs. Instead of chasing compounds that reduce lipophilicity could you attempt synthesis of compounds that block the metabolite Hypha identified such as

![combat Hypha metabolite](https://user-images.githubusercontent.com/87489802/153685116-c30bb586-41cc-458e-b321-07e7bb393020.jpeg)

**Comment by drc007** [comment]
> @drc007 I can't figure out which structure you are referring to - can you include an image, please?
![Screenshot 2022-02-11 at 11 19 57](https://user-images.githubusercontent.com/7080516/153702838-88779758-33d4-4efa-987f-01bc31f49fea.png)

Looks like the image did not attach to my email response.

**Comment by lferrins** [comment]
I just checked our inventory and we haven't made that compound previously. Sorry!

**Comment by danielgedder** [comment]
Hello everyone, 
We have the starting material to perform  Suzuki Coupling, maybe 100 mg of 3-bromo-2-(pyridyl)imidazole. I also took a look in our stock and picked up the most interesting boronic acids. I started the synthesis of analog 5 and I can synthesize the other analogs (6, 7 and 8) in the next few days. We have all the starting material to synthesize more 3-bromo-2-(pyridyl)imidazole.
We can purchase other boronic acids for more analogs (please, take a look at the list below). And some of the compounds that I proposed previously, the boronic acid are too expensive.  Then, I selected only boronic acids that we can afford.

![on progress](https://user-images.githubusercontent.com/88835924/154058890-691676e3-8527-473f-9fd6-638f41bbfa52.jpg)

**Comment by flavioemery** [comment]
@danielgedder you can always synthesize the boronic acids. If you have the aryl chlorides, you can prepare easily. See it here: https://pubs.acs.org/doi/10.1021/ja1089759

Maybe it is a good way to expand the library.

**Comment by mattodd** [comment]
@QSimpson the thing about that Hypha result is that I just don't know if it's a liability. The data we obtained [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Metabolic-Clearance-Data#adme-data-june-2021) shows compounds that are vulnerable to exactly that oxidation, but which have good (green) clearance numbers. Is it a real problem? Ditto @drc007 is your suggestion aimed at addressing the same thing?

@danielgedder buying some of those boronic acids seems sensible at those prices. I'd not bother with the cyclohexyl - logP too high.

@loriferrins some of those modified cores look interesting, and maintain key things (low logP, coordinating N, para-CN). Do you have synth capacity, or are you asking @danielgedder ;)

(@loriferrins We should be sure that all compounds made here are also entered into the screen for L. infantum etc, right? i.e. that we retain stock for that?)

**Comment by drc007** [comment]
Yes

Chris

**Comment by mariadichiara** [comment]
> I was just looking through the SAR summary in [issue 94](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/94) and was scribbling some ideas that I don't think we have tried yet (someone fact check me?). I was aiming to keep the cLogP in the vicinity of 2 (or slightly lower). Obviously, if some of these work (like replacing the pyridine with the pyrimidine) you could imagine different regioisomers.
> 
> I'm not sure that we have ever tried to truncate the bicycle down to the imidazole, though I am not convinced we should go in with the -NH free, or if we should use N-methyl imidazole? Thoughts from the group on that one?
> 
> @drc007 I can't figure out which structure you are referring to - can you include an image, please?
> 
> ![image](https://user-images.githubusercontent.com/65637708/153672001-9bef55a7-4a78-4baf-b5b2-e93c8760a598.png)

I could prepare analogs 1, 4, 5!

**Comment by lferrins** [comment]
Thanks, @mariadichiara - I'll get 2 and 3 into the synthesis queue separately!

**Comment by danielgedder** [comment]
Hello everyone, 

@mariadichiara, I can easily synthesize analog 1, because I have already started the synthesis diarylimidazole and at the same time  I have ready the precursor to performing Suzuki coupling. We have Pyridin-4-ylboronic acid in stock. 

Thank @flavioemery! I will also try to synthesize boronic acids.

**Comment by mariadichiara** [comment]
@danielgedder sounds good to me! Thanks

**Comment by edwintse** [comment]
I've updated the results image above with the missing solubility data

**Comment by MFernflower** [comment]
![4‐ 2‐(pyridin‐2‐yl)‐5H,6H,7H‐pyrrolo 1,2‐ a imidazol‐3‐yl aniline](https://user-images.githubusercontent.com/3164942/154699010-d94e1274-7d0a-4099-8ecf-10b9e81ba423.png)


Might be worth doing to improve water solubility

**Comment by lferrins** [comment]
> 821, 875, 975 and 1018 all have significantly higher microsomal clearance when compared to the hepatocyte clearance. Because of the large discrepancy between the assays doesn't this suggest uptake rate limited metabolism for the hepatocyte assay? They also have a spread of "ideal" LogDs. Instead of chasing compounds that reduce lipophilicity could you attempt synthesis of compounds that block the metabolite Hypha identified such as
> 
> ![combat Hypha metabolite](https://user-images.githubusercontent.com/87489802/153685116-c30bb586-41cc-458e-b321-07e7bb393020.jpeg)

@QSimpson can you share the synthetic route that you had sketched out for this analog?

**Comment by MFernflower** [comment]
@danielgedder  could you open a new Github Issue on what compounds you plan to make?

**Comment by danielgedder** [comment]
Closing: data incorporated into wiki: https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Metabolic-Clearance-Data 
Discussions of the planned compounds to be synthesized is here #112
