### ISSUE TITLE
MRSA Potency Assay and Results Jan 2022

### ISSUE THREAD

**Issue by edwintse** [opensourceantibiotics/Series-2-Diarylimidazoles#109]
The following 10 compounds have been screened against MRSA and MSSA by Paul Stapleton here at UCL. Identifying numbers below compounds are OSA numbers. The MIC values (ug/mL) are shown below for each bacteria. Colour coding: 2 and 4 (green); 8 and 16 (orange); 32 and >32 (red).

MSSA, methicillin-susceptible Staphylococcus aureus ATCC 25923; MRSA, methicillin-resistant Staphylococcus aureus NCTC 13373 (mecA-positive).

Results with 2 values (i.e. X/X) indicate 90% growth reduction/complete growth inhibition

![Untitled Wiley-1](https://user-images.githubusercontent.com/18062981/150522616-320b3377-4d49-499f-9444-d89f48e8336a.jpeg)

-----

**Quick Observations**

- The re-test **1029** continues to have 8 ug/mL activity
- Most of the core N-transposition results in poor activity with the exception of **1038**
- A methoxy on the pyridine ring appears to be helping (**1034**)
- An extra methylene between the core and the N-linker doesn't help (**1040**)

**Comment by danielgedder** [comment]
Closing: data incorporated into wiki: [Series-2-Diarylimidazoles](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles) SAR folder.

**Comment by mattodd** [comment]
...and just to check @danielgedder the data are in the relevant SAR page in the wiki?

**Comment by danielgedder** [comment]
> 

I updated the wiki page: https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Potency-Evaluation-and-SAR
