### ISSUE TITLE
New Clearance Data Incoming from Lori

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#111]
New ADME data came in Feb 4th from @loriferrins and uploaded [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/tree/master/Metabolism/NEU%20AZ%20Results%20Jan%202022).

Thanks for sorting @loriferrins !

@edwintse if you've bandwidth could you please convert to an image to help the humans, and add it to the appropriate place on the [wiki page](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Metabolic-Clearance-Data)? We'll need to add in relevant data to the image for the paper, too, if needed, but let's see which compounds we'll have in the main paper vs the SI first.

**Comment by edwintse** [comment]
Image added to #104 and to wiki
