### ISSUE TITLE
First round synthesis

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#16]
UCL labs are open (!) so @edwintse and I are getting started on synthesis. Our planned route and first targets are summarized below: 

![image](https://user-images.githubusercontent.com/53487492/87790924-3f5d6d80-c839-11ea-90b4-1341f35889b8.png)

(Access a [ChemDraw version](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Misc%20Contributions/SM_pricing.cdx) of this scheme.)

**Comment by mattodd** [comment]
So exciting @danaklug. Lab notebooks are [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Submissions-and-Sources-of-Data#lab-notebooks) (@edwintse add yours to the list then remove this comment or I can). (Dana you've an amusing Br masquerading as a boron). So the rationale is that the first two are the two controls (one is the known active, and one is the "parent" for which we have no data), and in the others we're playing with the thiophene to improve clearance parameters as per discussion in #8. That's it, right? I'll post an updated on other things we discussed in a moment.

**Comment by AlvaroLor** [comment]
Great! Just to know, what conditions are you going to use to make the boronic ester intermediate? and why are you planning to use the boronic ester without purification (or this is what I understand from the reaction scheme)?

**Comment by danaklug** [comment]
@AlvaroLor In the past I've used Bpin, KOAc, and Pd(dppf), so we'll give those conditions a go first. We'll try and purify it - this scheme is just for quick reference as to the overall route!

**Comment by MFernflower** [comment]
@danaklug Is some of the brominated core gonna be saved for things like coupling it to morpholine?

https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Misc%20Contributions/june_2020_mfernflower_proposed.svg

**Comment by MFernflower** [comment]
@AlvaroLor What @danaklug  is using is what was described in the original paper by Miyaura: 

Palladium(0)-Catalyzed Cross-Coupling Reaction of Alkoxydiboron with Haloarenes: A Direct Procedure for Arylboronic Esters
T. Ishiyama, M. Murata, N. Miyaura, J. Org. Chem., 1995, 60, 7508-7510.


A newer method can be found here *: https://www.organic-chemistry.org/abstracts/lit6/333.shtm

*Subject to catalyst availability! - ![EcktkQWXkAATbGh](https://user-images.githubusercontent.com/3164942/87841393-e4e10300-c872-11ea-90f6-56fb1dc36d46.jpg)

**Comment by AlvaroLor** [comment]
😂 Thanks @MFernflower ! The classical procedure is the most reasonable, I just wanted to know another one to add to my chem toolbox!

**Comment by MFernflower** [comment]
That catalyst is only two steps to make from a commercial intermediate:
https://shop.porphychem.com/products/5-10-15-20-tetra-p-tolyl-porphyrin.html
@AlvaroLor

>

**Comment by MFernflower** [comment]
@danaklug A 50/50 mix of THF and DMF has been used for Ni catalyzed boron transfer reactions but not certain for the Pd ones - Pretty hard for me to get info on this since it seems this area of chem is paywalled to heck and back (pun intended)
