### ISSUE TITLE
OSA Series 2 Meeting 17th July 2020

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#17]
(Didn't record it, sorry, but we _should be doing that_. In the Zoom were me, @danaklug  and @edwintse.

First meeting after UCL lab lockdown! Headline: chemistry re-starting.

1) **Community updates**: We need meetings like this on Youtube. We need more science update tweets. Let's make a video, using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3).

2) Are relevant **lab books** clearly linked? Yes, mostly [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Submissions-and-Sources-of-Data#lab-notebooks).

3) We're waiting for confirmation that the relevant samples that are in a **fridge at UNC** and are still available. Mat to ping the team (incl @AlvaroLor).

4) **Mechanism of action:** Lee Graves at UNC contacted re relevant experiments (#15). He's asked about the "base cell type" for the experiment. Don't understand this Q, so will seek clarity from the team.

5) **Monash measurement of _in vitro_** PK. #13 Green light to ship. 3-4 mg each, accurately weighed. The team have sent the necessary customs forms. Mat to forward to UNC and thank the Monash team.
 
6) Who is doing the **MRSA and tox screening** for all analogues? Mat to chase Paul Stapleton and Andreas Schatzlein within UCL SoP who have expressed interest and willingness. Other potential bio testing labs welcome, obviously.

7) **Synthetic Chemistry.** @danaklug  has shared the nice immediate chemistry plan (#16), which involves resynthesis of active and inactive controls, then variation in the thiophene part of the structure. @edwintse and @danaklug  to divvy up synthetic tasks and to seek now new commercially available starting materials that will allow simple variation of imidazole part of structure.

8) **Compound numbering**. Adopt code system from opensourceantibiotics/murligase#9 and [here](https://github.com/OpenSourceMycetoma/MycetOS-Tech-Ops/wiki/The-Molecule-Numbering-Convention) that captures batch and salt codes (_Done for Series 2 molecules to date_). Update the [supersheet](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit?usp=sharing) with corrected numbers and codes. Will probably need to address this also for OSA Series 1 at some point, lower priority.

9) Some interest from Pfizer (TBC) in assessing the molecules for **metabolic transformation (and isolating** the metabolites). Mat to confirm. 

10) We only have money currently for about 9 _in vitro_ PK evaluations from Monash, plus on final _in vivo_. It'd be very useful to have a **rough, high throughput experimental assessment of metabolic liability**. What can we use? #7 ? Academic or industrial interest? @danaklug to share search she's done.

11) **Design criteria** for molecules must keep an eye on logP (use Datawarrior) and predicted clearance (use SMARTCyp, right @drc007 ?).

Any and all comments please go ahead. We'll try to cross off all the above when done before closing this issue.

**Comment by danaklug** [comment]
@mattodd re: point 8 - I've updated the Series 2 molecules with salt and batch codes (new columns in the spreadsheet).

**Comment by mattodd** [comment]
Closing since we've moved on to #19
