### ISSUE TITLE
Info on SB-400868

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#2]
The MRSA MIC for the original **SB-400868** is not included in the grant proposal and I'm not sure who has this data - we need to track it down as it will be very useful for comparison of focused array compounds.

Also, just for the sake of completeness - can anyone confirm that **SB-400868** was identified as a hit through PKIS screening? It seems the most likely source to me but I don't know for sure.

**Comment by mattodd** [comment]
Hi @TwistedSwisster - further to general query in #4 do you have a source of data on this original compound? Any info greatly appreciated. 

Is Alvaro on Github yet? Perhaps we could encourage?

**Comment by danaklug** [comment]
Yes, Alvaro did respond to #8 a while ago... @AlvaroLor any info?

**Comment by mattodd** [comment]
Great, thanks! @drc007 could you please also add Alvaro to OSA if not already member?

**Comment by AlvaroLor** [comment]
Hi all! 
@danaklug you are right, **SB-400868** is a compound from PKIS. This compound was originally generated in an effort targeting ALK5/TGFBR1. However, a PKIS screening identified **SB-400868** as a hit against _Mtb_. Then, Bill and me designed the ALM-DAI library to optimise the molecule and we found that these analogues showed great MRSA MIC values.

As far as I know, **SB-400868** wasn't submitted for testing, and as we were the first to identify the activity of this compound series on MSRA, no MIC data are available for **SB-400868**. It makes a lot of sense to get the MIC value especially if we want to compare the results with the parent compound.

**Comment by drc007** [comment]
Not sure if you noticed the activity recorded in ChEMBL SB-400868 (CHEMBL268889) Inhibition of Activin like receptor kinase 5, TGF beta type I receptor = 460 nM.

**Comment by danaklug** [comment]
@AlvaroLor Thanks, that's really helpful! We will plan to resynthesize and submit SB-400868 for testing.

@drc007 Yes, that activity is something we should definitely be keeping an eye on in the future. (For the sake of comparison to MIC, that works out to ~0.15 ug/ml of SB-400868 - much less than the MIC of any of the array compounds against MRSA.)
