### ISSUE TITLE
The morpholine

### ISSUE THREAD

**Issue by MFernflower** [opensourceantibiotics/Series-2-Diarylimidazoles#21]
While I doubt this compound will be potent (but would be fantastic if it is!!!!) being so different than what we screened previously, the fact it could probably be made in a solvent free system using the bromo core, morpholine, and DIPEA in a inert gas filled microwave reaction vial is alongside it's rather good predicted metabolic stability is rather appealing.

Would @edwintse or @danaklug be willing to make a few milligrams? 

![367238638](https://user-images.githubusercontent.com/3164942/88559790-4a638b00-cffb-11ea-92c8-ed45bb859ab1.png)

**Comment by danaklug** [comment]
Yes, I also doubt it will be potent given some of the SAR that's been established through the focused array screening. Data's better than guesses though, so as long as we have enough of the core left after we make the high priority compounds we'll give it a go.

**Comment by bendndi** [comment]
@MFernflower  Compound quite close to this one in the list I just shared
https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/27#issue-701213991

**Comment by MFernflower** [comment]
@danaklug @edwintse Should just be normal Buchwald–Hartwig conditions i'd assume?

**Comment by MFernflower** [comment]
@danaklug @edwintse Need to add this compound to the graphic then we can close issue

**Comment by MFernflower** [comment]
SAR has changed massively during this period - closing

**Comment by mattodd** [comment]
Probably a good idea. When closing issues always try to think how to avoid orphaning them. Is there somewhere (e.g. wiki, Google sheet) that a link can be installed so that this Issue is connected to something? Don't know the answer, just uneasy about orphaned discussions (while at the same time very happy to close issues that are no longer needed).
