### ISSUE TITLE
OSA2 meeting Friday Aug 21st 2020

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#23]
Meeting 31/7/20 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #22.

Recording is [here](https://youtu.be/LPcbZEa6njs). On the call: me, @danaklug, @edwintse (we didn't advertise this meeting (sorry @AlvaroLor @drc007 @MFernflower but it's a regular slot at the same Zoom link each time)

1) UNC team (Carrow Wells) confirmed required samples are available in fridge. Need to forward to Monash (**Action** on Mat). COMPLETED - the two teams are now in touch.

2) **Mechanism of action:** Lee Graves at UNC was contacted re relevant experiments (#15). He asked about the "base cell type" for the experiment. We clarified MRSA is the cell type. Need now to start these experiments with active and inactive. (**Action** remains on Mat to ask for these experiments to be done)

3) **Monash measurement of _in vitro_ PK**. #13 Green light to ship. 3-4 mg each, accurately weighed (though UNC compounds are, it seems, DMSO solutions). The team (Karen White) have sent the necessary customs forms. Mat has thanked the Monash team and will forward requirements to UNC. We have money currently for about 9 _in vitro_ PK evaluations from Monash, plus on final _in vivo_. As for item 1, above, this is COMPLETED. But need to monitor progress with the shipping. **Action on Dana**.

4) **MRSA and tox screening** for all analogues. Mat has chased Paul Stapleton and Andreas Schatzlein within UCL SoP who have confirmed interest and willingness. There are possible delays owing to emerging from lockdown. Mat has also contacted CO-ADD, who carry out these assays, to see if they are interested. Any other solutions here? Or we proceed? TBD. **ACTION ON MAT** to establish timelines for SoP testing. Public Health England? Other possibilities? **Action on Ed** to do some quick searches.

5) **Synthetic Chemistry** Update was given in meeting by @edwintse and @danaklug and may be found below (insert link to file on GH then delete this @edwintse @danaklug **Action on @edwintse**). Impurity was mentioned in NMR spectrum - @danaklug to post below to see if we can ID. We currently have about 5-ish compounds. Aiming for something like 15 in 2 weeks or so. Ideally first shipment for eval in 1-2 weeks.

6) **Compound numbering** for compounds now being synthesised: adopt code system from opensourceantibiotics/murligase#9 and [here](https://github.com/OpenSourceMycetoma/MycetOS-Tech-Ops/wiki/The-Molecule-Numbering-Convention) that captures batch and salt codes. Update the [supersheet](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit?usp=sharing) with corrected numbers and codes. _Done for Series 2 molecules to date_. Will probably need to address this also for OSA Series 1 at some point, lower priority. Action on Dana to install note on numbering (e.g. in https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Synthetic-Chemistry). Marked as complete. COMPLETE.

7) Mat has confirmed the interest from Pfizer in assessing the molecules for **metabolic transformation (and isolating** the metabolites). These would be _pro bono_ biotransformations on a couple of compounds (they need a couple of mgs per compound). Scott Obach suggested a single methyl at the 2-position of the thiophene could stop clearance if that is where the molecule is being oxidised. Send active/inactive..? Ready to go? Got 100 mg thiophene active. Inactive...? Could we make one with single chemical step? **Action on Dana and Ed to consider synthetically accessible inactive control** which would also be useful for MRSA screening. Scott also offered to broker an intro to a UK company, Hypha, which he has now done. Action on Mat was to follow up, which is complete and awaiting reply. **Action on Mat to discuss with Hypha possible collaboration.**

8) Is there a **rough, high throughput experimental assessment of metabolic liability**. What can we use? #7 ? Academic or industrial interest? @danaklug to share search she's done but it doesn't look like there is a "standard _in vitro_ metabolic cocktail". Update - we can't really find anything, so let's stay with in silico. Marked as complete, but can keep #7 open. COMPLETED. 

9) The *similarity landscape*: David Drewry (UNC) very kindly put Mat in touch with James Callahan, the corresponding author on the original article reporting these compounds. Mat discussed with him the series history, and whether there were data and samples that could be shared. **ACTION on Mat** to draft conversation outcome and get clearance from GSK for sharing publicly. 

10) Recurring:
**Design criteria** for molecules must keep an eye on logP (use Datawarrior) and predicted clearance (use SMARTCyp). Update: also FAME <-- @drc007 contacted the team, they have emailed Mat and Mat will digest and report back.

**Community updates** (standing item, to make sure it's acted upon): We will post weekly meetings like this on Youtube. We need more science update tweets and little videos, using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3). <--Good time would be when we get first MRSA results.

AOB: Target Product Profile work that Dana was doing (#12). Nothing found that was MRSA-specific. Webinar from DNDi was attended by @danaklug and @drc007. Question: single-pathogen projects any use? Sometimes not - clinic likes broad spectrum. These compounds more useful for acute last-resort (<-- expensive trials) infections. What were the CO-ADD results?  Dig out to check activity against other bacteria ([Dana did this](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/22#issuecomment-667503470)). Did we have the activity report from CO-ADD? Not yet. Need. **Action on Dana** - can we secure original report from @AlvaroLor or @TwistedSwisster ? Important conclusion from this is that we don't know if active against other gram +ves. Need eval against other gram +ve. **Action on Ed**: how to get activity against other Gram +ve?

Actions (can be checked as complete after the meeting).

- [ ] ACTION ITEM: Mat to ask Lee/Carrow to begin MoA experiments with MRSA as the cell type.
- [x] ACTION ITEM: Dana to monitor shipping of compounds from UNC to Monash and chase in a week's time.
- [ ] ACTION ITEM: Mat to chase SoP-based MRSA and tox screening.
- [ ] ACTION ITEM: Ed to check if there are other MRSA and tox screening services in UK that could be employed.
- [x] ACTION ITEM: Dana and Ed to identify and make a synthetically accessible inactive control
- [ ] ACTION ITEM: Mat to discuss collaboration possibilities with Hypha.
- [ ] ACTION ITEM: Mat to clear with GSK what can be shared publicly about the series history.
- [ ] ACTION ITEM: Mat/Chris to report about possible use of FAME as a software tool.
- [ ] ACTION ITEM: Dana to dig out original CO-ADD screening report.
- [ ] ACTION ITEM: Ed to check whether we can obtain activity data against other gram positives
- [ ] ACTION ITEM: Mat This meeting video to be posted on YouTube.

**Comment by drc007** [comment]
Another web-based metabolism prediction tool. https://nerdd.zbh.uni-hamburg.de/gloryx/

**Comment by AlvaroLor** [comment]
@danaklug I was thinking what can be the problem with the final compound **DMK127-1**. When you see that the dehalogenated derivative is the main product tipically is because the coupling reaction is not fast enough. I have dealed with that many times and I would recommend you:
- Use a different Pd source and ligand such as Pd(dba)3/XPhos.
- Increase the eq of Pd.
- You can also prepare the mixture of Pd/ligand separately and then add it to the reaction mixture. There is an excellent paper by Buchwald (https://www.nature.com/articles/nprot.2007.411). You can use the "(B) Preparation of a catalyst stock solution" method.
- Lastly, if none of the above works I would suggest to change the solvent mixture. As the only difference between **DMK127-1** and the other DMK compounds is the boronic esther employed, it could be a solubility problem.

I hope this can help!

**Comment by MFernflower** [comment]
Bis(tri-tert-butylphosphine)palladium(0) might be what you are looking for but it's a little pricy and air-sensitive even when in the bottle. @danaklug @AlvaroLor

**Comment by mattodd** [comment]
Further to what we were talking about briefly earlier @danaklug I guess the mass spec will tell you something about whether perhaps you have a salt/protonated species? The NMR might give a clue to this if the integral is roughly consistent with a single H, for example, and whether the integral changes with hivac or changes between different samples (i.e. is this a part of the molecule or an impurity). I can imagine that the pyridine and adjacent N chelate a proton, so does the corresponding phenyl compounds @edwintse made have anything like this? Are the pyridine H signals shifted downfield from where you'd expect them?

**Comment by edwintse** [comment]
Update on the NMR issue above:
It appears that the mystery peak is coming from the CDCl3 that was used. I have taken the NMR spectra of the same compound (DMK 124-2) in my bottle of CDCl3 and the peak is not there. Also it seems that the shifts are slightly different, matching closer to what @AlvaroLor had.

Top spectra is using Dana's bottle of CDCl3
Bottom spectra is using my bottle of CDCl3

<img width="1097" alt="DMK124-2" src="https://user-images.githubusercontent.com/18062981/93226298-125f0580-f76b-11ea-85b5-a29b617cb026.png">

We will retake the NMR spectra of the other 2 compounds as well.
