### ISSUE TITLE
OSA Meeting Friday Sept 4 2020

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#24]
Meeting 4/9/20 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #23.

Recording is [here](https://youtu.be/qwOvMzk-V0E). On the call: @danaklug @edwintse @drc007 

1) **Mechanism of action**: Lee Graves at UNC was contacted re relevant experiments (#15). Will now do. **Action**: Dana to chase this in 2 weeks.

2) **Monash measurement of in vitro PK**. Complete. Awaiting data. No action needed.

3) MRSA and tox screening. Paul Stapleton (UCL School of Pharmacy) ready to screen by next Wed. We will have ca. 10 compounds. **Action** on Mat to check how much needed.
Tox: delay in Schatzlein lab (due to lockdown), not as crucial. **Action** on Mat to monitor. No obvious alternatives.

4) **Pfizer Biofunctionalisation**: We have active and inactives to ship to them. We can do that now. **Action** on Mat to ask how much they need, etc. Note from @drc007: Need to verify activity of all compounds in MRSA assay.

5) **Hypha**: Mat has met and corresponded with the company. **Action** Mat to report back on what's possible _via_ collaboration. 

6) **Series Origin/Similarity Landscape**: Mat in touch with James Callahan (GSK), the corresponding author on the original article reporting these compounds. Mat awaiting clearance from GSK for sharing publicly, and (**Action**) will report back.

7) Design criteria for molecules must keep an eye on logP (use Datawarrior) and predicted clearance (use SMARTCyp). Update: also FAME <-- @drc007 contacted the team, details on wiki. **Action** on Dana to install these tools on wiki so that we can delete from agenda.

8) Community updates: Need video update using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3). When we get first MRSA results.

9) Gram+/Gram- results. Dig out activity report from CO-ADD? @AlvaroLor doesn't have it, so (**Action**) Mat to write to @TwistedSwisster to track it down, alternatively direct write to COADD. Question remains: are these compounds active against other gram +ves?

10) Synthetic Chemistry Update was given in meeting by @edwintse and @danaklug - slides below and posted in code area.
Key: inactive dimethoxy compound made DMK132-1, Dana proposed triazoles, which can be screened as mixtures. Ed has made control phenyl compound, which would be good substrate for alfone/sulfoxide analogs.

AOB: 
(after meeting): Dana previously mentioned impurity in NMR spectra (https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/23#issuecomment-678374720). Was this resolved?

Actions other than the chemical targets discussed (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Mat to monitor possibility of SoP-based tox screening.
- [x]  ACTION ITEM: Dana to chase MoA experiments on Sept 18th.
- [x]  ACTION ITEM: Mat to check how much compound needed for MRSA screening.
- [x]  ACTION ITEM: Mat to check how much needed for Pfizer biofunctionalisation experiments.
- [ ]  ACTION ITEM: Mat to report back on collaboration possibilities with Hypha.
- [ ]  ACTION ITEM: Mat to report back from GSK on what can be shared publicly about the series history.
- [x]  ACTION ITEM: Dana to install software tool links on wiki.
- [x]  ACTION ITEM: Mat to contact Bill Zuercher about original CO-ADD screening report.
- [x]  ACTION ITEM: Mat This meeting video to be posted on YouTube.

**Comment by MFernflower** [comment]
Not certain if I can attend tomorrow but i'll try

**Comment by danaklug** [comment]
Links to SMARTCyp, FAME, DataWarrior, and SwissADME have been added to "Submissions, Resources and Data" [wiki page](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Submissions,-Resources,-and-Data)

**Comment by edwintse** [comment]
Synthetic chemistry slides (n.b. it now appears that the direct oxidation to the sufone EGT 479-2 has instead led to the pyridine N-oxide compound):
<img width="1136" alt="Screen Shot 2020-09-04 at 7 14 36 pm" src="https://user-images.githubusercontent.com/18062981/92273287-fba2ee00-eee2-11ea-93df-80dc32a1da44.png">
<img width="1136" alt="Screen Shot 2020-09-04 at 7 15 11 pm" src="https://user-images.githubusercontent.com/18062981/92273296-ff367500-eee2-11ea-9ed8-d5cd9e0ab4c7.png">

**Comment by MFernflower** [comment]
Interesting that the sulfur monoxide compound is so unstable. The azide
click is a brilliant idea - ACS describes a quick and dirty Sonogashira
that might be of help:
https://pubs.acs.org/doi/10.1021/acs.jchemed.5b00030
