### ISSUE TITLE
OSA Meeting Friday Sept 11 2020

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#26]
Meeting Sept 11th 2020 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #24 .

Recording is [here](https://youtu.be/DutqAq2c4Mo). On the call: @mattodd @edwintse @AlvaroLor @danaklug @drc007 @bendndi @MFernflower 

1) **Mechanism of action**: Lee Graves at UNC has discussed relevant experiments (#15) with Carrow Wells (UNC) and Mat Todd. Scheduled for a week or so. Compounds to be used:
Active: OSA_000822 which is ALM-DAI-28 (the benzothiophene)
Inactive: OSA_000820 which is ALM-DAI-26 (the veratrole).
**Action**: Dana to chase this in 2 weeks.

2) **Monash measurement of in vitro PK**. Awaiting data. No action needed.

3) MRSA and tox screening. Paul Stapleton (UCL School of Pharmacy) has screened the first 9 compounds, data shown in #25. See also @bendndi comments [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/25#issuecomment-690909006).
**Next steps based on SAR data**: 
Tox: Mat has been working to have tox measured, and hopes to report back on this at the next meeting. **Action** on Mat to report.

4) **Biofunctionalisation**: Progress has been made this week in discussions with Hypha, suggesting a lower need for Pfizer biofunctionalsation experiments. Action on Mat will report back at next meeting.

5) **Series Origin/Similarity Landscape**: Mat was in touch with James Callahan (GSK), the corresponding author on the original article reporting these compounds. Mat awaiting clearance from GSK for sharing publicly, and (**Action**) will report back.

6) **Community updates**: Need video update using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3). When we get first MRSA results. Action on @danaklug and/or @edwintse to create 30 second video.

9) **Gram+/Gram- results**. Dig out activity report from CO-ADD? @AlvaroLor doesn't have it. Mat wrote to @TwistedSwisster to track it down, alternatively direct write to COADD. Question remains: are these compounds active against other gram +ves? @TwistedSwisster supplied the COADD protocol that was used, but not yet the potency report, so it is still not clear where the original potency data originated. To be resolved.

10) Synthetic Chemistry Update by @edwintse and @danaklug - slides below and posted in code area?
Triazoles? sulfone/sulfoxide analogs?

AOB: 
Dana NMR impurity (https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/23#issuecomment-678374720). Was this resolved?

Actions other than the chemical targets discussed (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Mat to report on possibility of SoP-based tox screening.
- [ ]  ACTION ITEM: Dana to chase MoA experiments on Sept 25th.
- [ ]  ACTION ITEM: Mat to report back on collaboration possibilities with Hypha.
- [ ]  ACTION ITEM: Mat to report back from GSK on what can be shared publicly about the series history.
- [ ]  ACTION ITEM: Mat to chase Bill Zuercher about original CO-ADD screening report.
- [x]  ACTION ITEM: Mat This meeting video to be posted on YouTube.
- [ ]  ACTION ITEM: Ed and Dana to make 30-second video highlighting the new potency data.

**Comment by bendndi** [comment]
Would love to join but I think I have a clash...

**Comment by MFernflower** [comment]
@mattodd @bendndi @edwintse This metabolite was mentioned briefly in this meeting so I will post it here: 

![OSA824](https://user-images.githubusercontent.com/3164942/92985905-ddaa3000-f484-11ea-8252-b48fac1d0ff1.png)

**Comment by mattodd** [comment]
This was a very good meeting thanks to all for contributing and in particular to @bendndi for the new insights in this project.

1) The key new data point from the _in vitro_ results #25 is that the "boxed" compound our analog series was based on, OSA_000812 is inactive. This alters the interpretation of much of the SAR (updated [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Potency-Evaluation-and-SAR)).

2) In parallel, it turns out that compounds with the benzoimidazole core, OSA_000814, have been investigated in another project involving DNDi and Lori Ferrins at Northeastern Uni. It is therefore important that this core is re-investigated, both through the acquisition of existing compounds and via the synthesis of the compound we had presumed might be inactive, which is this one (The One That We Want):

<a href="url"><img src="https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Meetings/Sept%202020/New%20Benzimidazole%20target.png?raw=true" align="centre" height="190" ></a>

C1(C2=C(C3=CC=C(SC=C4)C4=C3)N5C(C=CC=C5)=N2)=NC=CC=C1
InChI=1S/C20H13N3S/c1-3-10-21-16(5-1)19-20(23-11-4-2-6-18(23)22-19)15-7-8-17-14(13-15)9-12-24-17/h1-13H

Obviously this compound is becoming too flat and aromatic, and this is a future design consideration, in that we're likely to want to include more sp3 character. There is some structural similarity with Zolpidem.

Action is therefore to explore these avenues and source compounds/synthetic routes. Ben has just started this in #27.

It's obviously unusual to have an SAR table in a project where the "Compound in the Box" is inactive. It's doubly important for us to source the original report from COADD to confirm this result. It's also important we re-test our sample of compound 812 to be very sure of this conclusion. 

3) As mentioned by @drc007, it's important for Lee Graves to screen the compounds he's looking at for MoA against MRSA to ensure that they are still OK. **Action** on me.

4) Need to update the wiki with list of meetings held - can I put that on @edwintse? 
Also, the codes we're using - ensure we use the full compound ID when we need to get specific (and in the Gsheet), but fine to include simple numbers in summary tables.

5) We should still screen Ed's N-oxide that was obtained (EGT479-2).

6) Ask Paul Stapleton to compare the MRSA potency methods he used with the COADD results and comment on any significant differences. **Action**.

6) Assuming that we want to continue with structures that are like 822 (our current best) then Ben was suggesting the following (to be modified after comparison with what's posted in #27 ):

a) Checking whether 3- and 4-pyr rings are effective. Originally we had thought these were inactive, but now it is possible they possess potency and they should be investigated. Also suggested by Ben were 3-pyrazole or 4-imidazole rings (shown), and some of these may be available already.

b) The Dana disconnection (in Ed's synthesis summary in the meeting (@edwintse can you share below?) is something that could be pushed as it allows the intro of the ring at a late stage.

7) Chris Swain asked whether we were likely to see any metabolic clearance in the MRSA potency assay. Good question. This seems unlikely, which would argue against a metabolite being responsible for the in vitro potency. **Action** Mat to check with Paul.

8) Dana NMR impurity [has been resolved](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/23#issuecomment-692768514) - moral is ... always check your CDCl3, I guess?

**Comment by MFernflower** [comment]
@mattodd I was kinda wondering if the lab could try running the MRSA assay
on Ambien but I'd assume a bunch of papers would have to be filled out.

**Comment by MFernflower** [comment]
@mattodd I had also proposed a compound starting from acetylpyrazine - a
common perfume ingredient

**Comment by edwintse** [comment]
<img width="723" alt="Screen Shot 2020-09-17 at 11 09 46 am" src="https://user-images.githubusercontent.com/18062981/93456968-502c6d00-f8d6-11ea-8c64-eb636449ad33.png">
