### ISSUE TITLE
OSA Meeting Friday Sept 18 2020

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#28]
Meeting Sept 18th 2020 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #26 .

Recording is [here](https://youtu.be/WcfalfBJxQ4). On the call: @mattodd @edwintse @danaklug @drc007

1) **Mechanism of action**: Lee Graves at UNC is conducting the experiments. Mat has emphasised the need to verify the MRSA potency in addition to the MoA work, and this will be possible at UNC.
**Action**: Dana to check in in 1 week.

2) **Monash measurement of in vitro PK**. Awaiting data. No action needed.

3) MRSA and tox screening. 
MRSA: Following Paul Stapleton's (UCL School of Pharmacy) first screen (#25) he has confirmed willingness to screen further compounds. 
Tox: **Action** still on Mat to organise tox screening. Of particular importance given comments on selectivity index from @bendndi [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/25#issuecomment-691936520).

4) **Biofunctionalisation**: **Action** still on on Mat to report about ongoing discussions.

5) **Series Origin/Similarity Landscape**: Mat is awaiting clearance for the GSK conversation and will report back when that's received.

6) **Community updates**: Need 30-second video update using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3) describing first MRSA results and to highlight new injections of compounds from @bendndi and collaborators.

9) **Gram+/Gram- results**. **Action** on Mat to re-contact @TwistedSwisster to track down original CO_ADD report and to try direct approach to CO_ADD. Question remains: are these compounds active against other gram +ves?

10) **Compound Donations**. Thanks to the excellent work of @bendndi we have three shipments of molecules incoming #27. Originating from Imperial (not yet confirmed), Northeastern (not yet confirmed) and TCG (confirmed shipping). The compounds feature the imidazopyridine core, originally considered to be inactive, but now being reassessed in light of the most recent potency data discussed [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/26#issuecomment-693695331). Dana is coordinating shipment deliveries. Methods from Lori Ferrins were received for the synthesis of these kinds of compounds and we'll see if we can post them.

11) **Synthetic Chemistry Update** by @edwintse and @danaklug - slides below and posted in code area? Note [design plans arising from last meeting](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/26#issuecomment-693695331).

AOB: 
12) **Action** on @edwintse to update wiki with list of meetings held.
13) Note: the informal codes we're using - are they aligned with the formal numbering system?
14) Ask Paul Stapleton to compare the MRSA potency methods he used with the COADD results and comment on any significant differences. **Action** on @danaklug 
15) Are we likely to see any metabolic clearance in the MRSA potency assay? This seems unlikely, which would argue against a metabolite being responsible for the in vitro potency. **Action** @danaklug to check with Paul S.
16) Other suggested compounds: @MFernflower to summarise other compounds suggested in this series in one fig along with SMILES strings, so we can capture them. 

Actions other than the chemical targets discussed (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Mat to report on possibility of SoP-based tox screening.
- [ ]  ACTION ITEM: Dana to chase MoA experiments on Sept 25th.
- [ ]  ACTION ITEM: Mat to report back on collaboration possibilities with Hypha.
- [ ]  ACTION ITEM: Mat to report back from GSK on what can be shared publicly about the series history.
- [ ]  ACTION ITEM: Mat to chase Bill Zuercher about original CO-ADD screening report.
- [x]  ACTION ITEM: Mat This meeting video to be posted on YouTube.
- [ ]  ACTION ITEM: Ed and Dana to make 30-second video highlighting the new potency data.
- [x]  ACTION ITEM: Ed to update wiki with meetings held.
- [ ]  ACTION ITEM: Dana to ask Paul S about comparison of MRSA assays and extent to which we might see oxidation in his assay (i.e. could metabolites be the actives?)
- [X]  ACTION ITEM: Mandrake to summarise other suggestions for compounds alongside their SMILES. Update: (All of his compounds but one are now in Ed and Dana's sheet!)

**Comment by edwintse** [comment]
Synthetic update slides from the meeting. Powerpoint with all update slides to date put in the code tab as well.
![Untitled Wiley Document-3](https://user-images.githubusercontent.com/18062981/93603216-9c051200-f9bb-11ea-87e0-990d5316f924.jpeg)

**Comment by MFernflower** [comment]
@mattodd Ed's graphic has captured what I have suggested beside the
morpholine compound that has a ghi open

>

**Comment by danaklug** [comment]
@drc007 has pointed us to [this paper](https://onlinelibrary.wiley.com/doi/epdf/10.1002/anie.202010631) re: 2-pyridyl Suzuki couplings. In particular the suggestion that "the 2-pyridyl problem can be circumvented by the formal inversion of polarity of the coupling partners" points to the use of 2-bromopyridyl as a possible way to get the reaction to work. I've received this compound so now just have to successfully borylate the imidazole to try those conditions. Thanks Chris!

**Comment by MFernflower** [comment]
@danaklug might also need to change the songoshira conditions  if low yield- dmf as solvent and palladium triphenylphosphine as catalyst?
