### ISSUE TITLE
OSA Meeting Friday October 16 2020

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#33]
Meeting Oct 16th 2020 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #32  .

Recording is [here](https://youtu.be/gl4ippR1x1k).

On the call:

1. **Screening**.
MRSA: Next screen next Tuesday. Comparison of MRSA potency methods + discussion of metabolic clearance in the MRSA potency assay posted in comments of #32 
Tox: Can start next week in lab of Andreas Schatzlein, being arranged by @danaklug. Which compounds to test?
Other Gram positives: @MFernflower suggested investigating activity vs Streptococcus pyogenes (can Paul Stapleton do this?). Are there other Gram+ves that are WHO high priorities? (YES - Enterococcus faecium) Perhaps lack of activity vs Gram -ve is due to accumulation problems? (will wait to see what MoA might say).

2. **Synthetic Chemistry Update** by @edwintse and @danaklug 

3. **in vitro PK**: Monash data discussed in #29. 
a) Residual uncertainty about the units between original data and those from Monash. Comparable? Check inherited data to be sure. **Action**: Mat.
b) **Benzofuran compound (821)** will be evaluated for metabolic ID etc. More "drug-like" than the benzothiophene lead - Compound has been resynthesized by @edwintse which is great.

4. **Community updates**: Need 30-second video update using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3) describing first MRSA results, to highlight new injections of compounds from @bendndi and collaborators, and to highlight new data from Monash. Action on @danaklug @edwintse to do a 30-second thing we can post <-- this isn't going away, guys...
-Mailing list?

5. **Inherited data** @TwistedSwisster kindly provided original CO_ADD report (#31). No testing vs. against other gram +ves?
Important new data on tox: not a huge selectivity window. However, the tox numbers are very flat across the molecules tested, meaning the tox may derive from a constant feature of the structure, e.g. the metal-binding potential of the 2-pyridyl system. **Experiment to do**: re-synthesize (if needed) and evaluate (for human cell tox) the phenyl (EGT 482), 3 and 4-pyridyl analogs to check if the 2 pyridine functional group is responsible.

AOB:

6. **Mechanism of action**: Experiments ongoing (see #30). Check in in a couple of weeks.

7. **Biofunctionalisation**: **Action** still on Mat to report about ongoing discussions with Hypha.

8. **Series Origin/Similarity Landscape**: Mat is awaiting clearance for the GSK conversation and will report back when that's received.

Actions other than the chemical targets discussed (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Mat to report back on collaboration possibilities with Hypha.
- [ ]  ACTION ITEM: Mat to report back from GSK on what can be shared publicly about the series history.
- [x]  ACTION ITEM: Mat This meeting video to be posted on YouTube.
- [ ]  ACTION ITEM: Ed and Dana to make 30-second video highlighting the new project inputs.
- [ ]  ACTION ITEM: Mat to look into possible email update list using e.g. Mailchimp.

**Comment by MFernflower** [comment]
@danaklug A freindly reminder to open a github issue for the screen results before the upcoming MRSA screen results come in

**Comment by danaklug** [comment]
Link to this Issue has been created in "Project Meetings" wiki.
