### ISSUE TITLE
Draft Email Update Oct 2020

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#34]
Dear Friend of Open Source Antibiotics (OSA),

It's been a busy few months in OSA. Recent activity is being captured in our weekly public Zoom meetings (every Friday at 2pm London at https://ucl.zoom.us/j/92800004715), and you can see the details in the recordings of those meetings (like [this one](https://www.youtube.com/watch?v=gl4ippR1x1k&feature=youtu.be)) and the associated "Github Issues" (like [this one](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/33)).

<a href="url"><img src="https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Meetings/Oct%202020/Screen%20Shot%202020-10-21%20at%203.33.38%20PM.png?raw=true" align="centre" height="250" ></a>

But as part of those discussions we were wondering about _the best way to update everyone quickly_. While OSA uses [Twitter](https://twitter.com/OSantibiotics), there is no good substitute for a short email. So this is our first, short OSA news email. Three points:

1) We have guessed you're interested in receiving occasional emails about OSA. If you're not, just email us back to say you'd like to opt out. Nobody likes spam.
2) Please forward this to anyone you think might be interested in antibiotics or drug discovery or open science. As an open project, everything is in the public domain, and everyone is welcome. 
3) To keep things short, each news email has a limit of three items. If you're interested in learning more, then each project has a wiki (current project status, like [this](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki)) and the Issue Tracker (current To Do list and discussion, like [this](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues)).

So - drumroll - here is the first quick update, focussing on OSA Series 2 (we'll update on Series 1, the mur ligases, soon).

1) We have [confirmed the activity](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Potency-Evaluation-and-SAR) _vs_ MRSA of the diarylimidazoles (exemplar compound OSA821 shown below), originally discovered and explored by Alvaro Lorente and Bill Zuercher at UNC Chapel Hill. [A new potency screen is being performed this week](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/35) at UCL by Paul Stapleton, and includes about 30 compounds that have been donated to the project via Ben Perry (DNDi). This time our potency assay will include a parallel screen of select compounds _vs_ VRE, to see if there is activity _vs_ other high priority Gram +ves. 

<a href="url"><img src="https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Synthetic%20Chemistry/OSA821.png?raw=true" align="centre" height="190" ></a>

2) A key aim of the project is to solve the rapid clearance of the known actives. [New data from Sue Charman's lab](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Metabolic-Clearance-Data) gave clues as to which compounds to investigate next, and we are finalising negotiations for some _pro bono_ work from a UK company towards identification of possible metabolites.

3) The mechanism of action of these compounds is unknown, but [Lee Graves's lab at UNC](https://www.med.unc.edu/pharm/directory/lee-m-graves-phd/) are in the middle of some [MIBs](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3691232/) experiments that we hope will reveal, by the end of October, some key new insights into how the compounds work.

Best wishes,

Mat and all the OSA Series 2 contributors

<a href="url"><img src="https://github.com/opensourceantibiotics/GeneralTopics/blob/master/Website%20Materials/Website%20Pix/OSA%20logo_low.jpg?raw=true" align="centre" height="190" ></a>

**Comment by mattodd** [comment]
I was wondering about whether we needed an OSA email address. But that would mean we'd need to share logins. How about we democratise it more simply - and we just take it in turns to send out the emails (which we can always write together). I'm not sure anyone likes "corporate" email addresses.

**Comment by mattodd** [comment]
OK @bendndi @drc007 @danaklug @edwintse @MFernflower any v quick comments? Want to keep it super simple and short - this one is a bit longer because it's first. Will test out the way pictures look when it's copied into an email.
For keeping the list of people it's sent to, we'll have to use a non-open Google sheet (for email address privacy). Suggestions welcome here for people, though.

**Comment by mattodd** [comment]
I'll mail you the link - currently ca 30. Occasional is fortnightly/monthly (depending on progress). This one focusses on Series 2, but the next might focus more on Series 1, the mur ligases.

**Comment by mattodd** [comment]
By the way I'm assuming you're happy (@drc007 @danaklug @edwintse @Giada-chem ) for the screenshot for the meeting to be in the email - it's public domain, but don't hesitate to ping me privately if you'd rather this didn't feature. Always nice to have smiling faces if we can...

**Comment by danaklug** [comment]
@mattodd Looks good to me!

**Comment by drc007** [comment]
Fine with me

**Comment by MFernflower** [comment]
All looks good

**Comment by mattodd** [comment]
Sent just now. Fortunately a copy and paste from the above directly into an email works well, with links and pictures transferred. I'll also tweet out a link in case people want to sign up to receive. I'll be seeking volunteers to mail out the next one. As the email says, feel free to circulate to others we're not currently engaging. Thanks for your inputs everyone. Future email updates can use the orange "newsletter" tag.

**Comment by drc007** [comment]
@mattodd OK to publish on my website?

**Comment by mattodd** [comment]
@drc007 absolutely

**Comment by drc007** [comment]
https://www.cambridgemedchemconsulting.com/news/index_files/dc6e67c12a522bbdb07d3bacd47715c3-446.html
