### ISSUE TITLE
MRSA/VRE Assay and Potency Results Oct 2020

### ISSUE THREAD

**Issue by edwintse** [opensourceantibiotics/Series-2-Diarylimidazoles#35]
The following 38 compounds have been screened against MRSA by Paul Stapleton here at UCL. In addition to this, all compounds will be screened against VRE (vancomycin-resistant _Enterococcus faecalis_) to see if our compounds are active against other gram +ve bacteria. The MIC values (ug/mL) are shown below for each bacteria. Colour coding: 2 and 4 (green); 8 and 16 (orange); 32 and >32 (red).

Top compounds synthesised by @edwintse and @danaklug including benzofurans and +ve and -ve controls (822 and 820, respectively). Bottom compounds donated from DNDi (Thanks @bendndi!)

![Assay compounds Oct 2020](https://user-images.githubusercontent.com/18062981/97081149-58c04380-15f8-11eb-9774-e7ae6a994451.jpeg)
----

**Quick observations**

- There is good correlation of activity between the gram +ve bacteria (MRSA and VRE)
- The positive control (**822**) had slightly decreased activity again (compared to the original of 2 ug/mL and the previous run of 4 ug/mL)
- The 5,6-core is tolerated better with the benzothiophene (**871**) => @danaklug currently pursuing the benzofuran derivative with this core
- Remake of the benzofuran (**821**) matches the original results => the 2-pyridyl is important as the phenyl, 3- and 4-pyridyl (869, 861 and 862 respectively) are inactive => need to evaluate this set for tox (#3)
- The p-tolyl compound (**865**) is also active
- All other UCL compounds are inactive
- The majority of the DNDi compounds (unsaturated 5,6-core with amine spacer) are inactive with a few exceptions that have weak activity => but tricky to make meaningful connections between these weak actives
---

OSA_000XXX | SMILES
-- | --
837 | CS(C(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4)(=O)=O
838 | CS(C(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4)=O
839 | COC1=CC2=NC(C3=NC=CC=C3)=C(NC4=CC=C(F)C=N4)N2C=C1
840 | CN(C)C(C=C1)=CC=C1C2=C(NC3CCCC3)N4C(C=C(C)C=C4)=N2
841 | CC1=CN2C(C=C1)=NC(C3=NC=CC=C3)=C2NC4=CC=C(OCCO5)C5=C4
842 | CC1=CN2C(C=C1)=NC(C3=NC=CC=C3)=C2NCC4=CC=CC=C4
843 | COC1=CC2=NC(C3=CSC=N3)=C(NC4=CC=CC(F)=C4)N2C=C1
844 | FC1=CC(NC2=C(N=C3N2C=C(CN(C)C)C=C3)C4=NC=CC=C4)=CC=C1
845 | C1(C2=C(NC3CCCC3)N4C(C=CC=C4)=N2)=NC=CS1
846 | CN(C)C(C=C1)=CC=C1C2=C(NC3=CC=C(F)C=C3)N4C(C=C(C)C=C4)=N2
847 | FC(C=C1)=CC=C1NC2=C(N=C3N2C=CC=C3)C4=NC=CN4C
848 | COC1=CC2=NC(C3=CN(C)C=N3)=C(NC4=CC=CC(F)=C4)N2C=C1
849 | CC1=CN2C(C=C1)=NC(C3=CC(OC)=C(OC)C=C3)=C2NCC4=CC=CO4
850 | C1(C2=C(N3CCOCC3)N4C(C=CC=C4)=N2)=NC=CC=C1
851 | COC1=CC2=NC(C3=NC=CC=C3)=C(NC4=CC=CC=C4F)N2C=C1
852 | FC1=CC(NC2=C(N=C3N2C=C(COC)C=C3)C4=NC=CC=C4)=CC=C1
853 | COC1=CC2=NC(C3=NC=CC=C3)=C(NCC4=CN(C)C=N4)N2C=C1
854 | COC1=CC2=NC(C3=NC=CC=C3)=C(NC4=CC=NC(C)=C4)N2C=C1
855 | COC1=CC2=NC(C3=CN(C)N=C3)=C(NC4=CC=CC=C4F)N2C=C1
856 | COC1=CC2=NC(C3=NC=CC=C3)=C([H])N2C=C1
857 | COC1=CC2=NC(C3=NC=CC=C3)=C(C4=CC=CC(Cl)=N4)N2C=C1
858 | COC1=CC2=NC(C3=NC=CC=C3)=C(C4=CC=C(F)C=C4)N2C=C1
859 | FC(C=C1)=CC=C1C2=C(N=C3N2C=CC=C3)C4=NC=CC=C4
860 | COC1=CC2=NC(C3=NC=CC=C3)=C(C4=CC=CC=C4)N2C=C1
821 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=NC=CC=C1
861 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=CN=CC=C1
862 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=CC=NC=C1
864 | N#CC1=CC=CC(C2=C(N=C3N2CCC3)C4=NC=CC=C4)=C1
865 | CC(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
866 | COC1=CC2=NC(C3=CNC=N3)=C(NC4=CC=C(OCCO5)C5=C4)N2C=C1
867 | COC1=CN2C(C=C1)=NC(C3=CNC=N3)=C2NC4=CC=C(OCCO5)C5=C4
868 | FC(OC(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4)(F)F
869 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=CC=CC=C1
870 | C1(C2=C(C3=CC=CC=C3)N4C(CCC4)=N2)=NC=CC=C1
871 | C1(C2=C(C3=CC=C(SC=C4)C4=C3)N5C(C=CC=C5)=N2)=NC=CC=C1
872 | FC1=CC(C2=C(N=C3N2CCC3)C4=NC=CC=C4)=CC=C1
822 | C1(C2=C(C3=CC=C(SC=C4)C4=C3)N5C(CCC5)=N2)=NC=CC=C1
820 | COC(C(OC)=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4

**Comment by MFernflower** [comment]
@danaklug Do we know when will the actual data will arrive?

**Comment by danaklug** [comment]
> @danaklug Do we know when will the actual data will arrive?

Hopefully in time for our meeting on Friday but otherwise sometime early next week.

**Comment by MFernflower** [comment]
@danaklug @edwintse If the VRE and MRSA data are going to be delivered as one chunk - I'd doubt it be ready by tomorrow 2PM UK but we have been surprised before! @mattodd 

I will attend tomorrows meeting anyway!

**Comment by drc007** [comment]
Would be good to have structures in SMILES format.

**Comment by edwintse** [comment]
UPDATE: The original post has now been updated to include the potency results and some quick observations. A table of SMILES strings have also been added.

**Comment by MFernflower** [comment]
@edwintse @danaklug @mattodd @drc007 

A few ideas I thought up after seeing the new data:

![new_ideas_mfernflower_oct_24_2020](https://user-images.githubusercontent.com/3164942/97081775-a6c25080-15d2-11eb-9cb3-a79412531eb4.png)

**Comment by drc007** [comment]
The fact that the 2-pyridyl is essential underlines the importance of getting the toxicity data on the same compounds.

**Comment by danaklug** [comment]
A few more observations about the DNDi set: 

- Methoxy- and methyl-substituted imidazopyridine cores are tolerated (858, 860, 839, 851, 855, and 841) and may improve MRSA activity (859 vs 858).

- Amine insertions are tolerated in many cases (839, 851, 855, 841).

- Replacement of 2-pyridyl with other heterocycles is not tolerated (no exact matched pairs, but none of these compounds show any activity). 

- Compounds without aromatic substituents at the northwest position are not active.

**Comment by MFernflower** [comment]
@danaklug @edwintse Might not be a bad idea to make a version of 839 where the fluoropyridine motif is replaced with the para-methylphenyl group of 865

https://molview.org/?smiles=COC1C=CN2C(=NC(=C2N([H])C2C=CC(C)=CC=2)C2C=CC=CN=2)C=1

**Comment by mattodd** [comment]
Activity _vs_ VRE (actually _Enterococcus faecalis_, vanB-positive; Paul says he will try and obtain a vancomycin-resistant _Enterococcus faecium_ strain for future reference) is roughly tracking with MRSA indicating the activity is likely not something that is MRSA-specific.

**Comment by MFernflower** [comment]
@mattodd I almost wonder if instead of sourcing another Enterococcus strain it would be better if we tried another pathogen on the list - Streptococcus pneumoniae is a promising one

**Comment by mattodd** [comment]
Quick thoughts on the data, since I'll be mobile on Friday and may not be able to dial in well (@danaklug has agreed to host the meeting). @bendndi @drc007 @loriferrins it'd be awesome if you were also able to join and give your gut feelings on the above data.

1) Compound 865 (the tolyl) is interesting, and this does indeed mean that exploration of that ring is a good idea (and synthetically simple) as @danaklug and @MFernflower have already suggested. We've retained activity and removed what was a significant metabolic liability (though we might have created a new one).

2) I'm also interested by 871, that the DNDi-style aromatic core works. The chimera with 865 would be interesting.

3) We seem to need the 2-pyridyl. We need to await the tox data (compounds being sent in #3 and data next week), but the fact that so many compounds contain the 2-pyridyl and yet are *inactive* does suggest we're not talking about a generic toxicity effect arising from that motif. There could still be a common target between mammalian and gram+ve, which would be problematic, but let's see.

**Comment by drc007** [comment]
Can everyone include calculated LogP with their compound suggestions.

**Comment by drc007** [comment]
Here is a sdf file with all 39 compounds together with a range of calculated physicochemical properties.

This can be viewed using the open source DataWarrior (http://www.openmolecules.org/datawarrior/download.html). 

[29Oct2020alldata.sdf.zip](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/files/5458613/29Oct2020alldata.sdf.zip)

**Comment by MFernflower** [comment]
@mattodd I can attend tommrow's meeting

**Comment by drc007** [comment]
A few thoughts. Why is the pyridyl nitrogen important? One possibility is that it takes part in a bidentate interaction as shown below in orange (there is no direct evidence for this), the low energy minima is shown in blue where the pyridyl nitrogen points away from the imidazole nitrogen. It might be interesting to do some NMR experiments to see if addition of zinc changes the preferred conformation?

<img width="1051" alt="Screenshot 2020-10-29 at 14 56 36" src="https://user-images.githubusercontent.com/7080516/97591071-25662600-19f7-11eb-9614-8e01fa4c495d.png">

Along similar lines perhaps look at eliminating one of the imidazo nitrogens. An alternative might be to explore alternatives to the pyridine that maintain a nitrogen that could form a bidentate interaction.



![821ideas](https://user-images.githubusercontent.com/7080516/97591855-f13f3500-19f7-11eb-92ba-88c0041734d4.png)

Whilst the benzofuran is the most active to date, the benzodioxan of OSA_000841 might be an interesting lower logP alternative (however the dimethoxy was inactive OSA_000820), perhaps the nitrogen linker is important.

**Comment by MFernflower** [comment]
@drc007 What about lopping off the core nitrogen that does not participate in the metal binding?

![alternativecore](https://user-images.githubusercontent.com/3164942/97596536-32751c00-19db-11eb-9773-fd31409eeac7.png)

**Comment by mattodd** [comment]
@drc007 Yes, @bendndi suggested playing with that pyridyl (yet keeping a coordinating atom, like your thiazole) back [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/26#issuecomment-693695331). Might make sense. Removing the imidazo N makes sense from a logical/academic standpoint to assess the metal binding.
I love NMR titration experiments. Nice idea, though I would be v surprised if it did not chelate in exactly this way.

**Comment by drc007** [comment]
@MFernflower I think that will exist as the pyrrole tautomer (hydrogen on the nitrogen).

**Comment by MFernflower** [comment]
@drc007 if I am not mistaken - the Zinc II ion would still be able to
access the nitrogen's lone pair even if it assumes that form in water -
it's been a while since I studied this so forgive me

**Comment by danaklug** [comment]
I've received materials to make these four compounds (brominated cores will be elaborated). The chloro compounds will also enable a Topliss analysis of the northwest substituent, which I'm hoping will generate ideas for further analogs.

![image](https://user-images.githubusercontent.com/53487492/97718846-4b0a3280-1abe-11eb-8c1d-25ef5e34c0ab.png)

**Comment by danaklug** [comment]
Closing - these compounds have been added to the SAR wiki.
