### ISSUE TITLE
OSA Meeting Friday October 23rd 2020

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#36]
Meeting Oct 23rd 2020 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #33.

Recording is [here](https://youtu.be/zZyns3I0z0I).

On the call: @mattodd @edwintse @AlvaroLor @Giada-chem @WieselHenson @drc007 @MFernflower  

1. **Screening**.
MRSA: Screen happening now: #35. Will include evaluation vs another gram+ve: VRE. @drc007 says that when we get the results back we may want to do a new reach out to see if people may have compounds that they might want to donate.
Tox: Starting soon in lab of Andreas Schatzlein, being arranged by @danaklug. #3. Tox is also to test the metal-binding potential of the 2-pyridyl system. To be evaluated: the phenyl (EGT 482), 3 and 4-pyridyl analogs to check if the 2 pyridine functional group is responsible.

2. **Synthetic Chemistry Update** by @edwintse and @danaklug 

3. **in vitro PK**: 
a) Residual uncertainty about the units between original data and those from Monash. Comparable? Check inherited data to be sure. **Action**: Mat.
b) **Benzofuran compound (821)** will be evaluated for metabolic ID.

4. **Community updates**
a) Need 30-second video update using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3) describing donations of compounds from @bendndi and collaborators? Action on @danaklug @edwintse to do a 30-second thing we can post <-- this isn't going away, guys...
b) First email newsletter sent #34. @drc007 raises the excellent point about GDPR - that people need to give their consent to be emailed, and we need a record of that. Hence may be easier to set up Google Form for sign-up?

5. **Inherited data** @TwistedSwisster kindly provided original CO_ADD report (#31). No testing vs. against other gram +ves, hence new screen vs VRE.

AOB:

6. **Mechanism of action**: Experiments ongoing (see #30). Check in in a couple of weeks.

7. **Biofunctionalisation**: **Action** Awaiting contract signing for further interactions with Hypha.

8. **Series Origin/Similarity Landscape**: Mat is awaiting clearance for the GSK conversation and will report back when that's received.

Actions other than the chemical targets discussed (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Mat to report back on collaboration possibilities with Hypha.
- [ ]  ACTION ITEM: Mat to report back from GSK on what can be shared publicly about the series history.
- [x]  ACTION ITEM: Mat This meeting video to be posted on YouTube.
- [ ]  ACTION ITEM: Ed and Dana to make 30-second video highlighting the new project inputs.
- [ ]  ACTION ITEM: Consider web form for signing up for newsletters.

**Comment by danaklug** [comment]
Just catching up and have a note on tox - we agreed last week that we'd wait for the latest potency data to finalize the list of compounds to be screened for toxicity. We should get discussion going on that on #3 and once we pick compounds I can get back in touch with Alex and Reno.

**Comment by danaklug** [comment]
Link to this Issue has been created in "Project Meetings" wiki.
