### ISSUE TITLE
OSA Meeting Friday November 20th 2020

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#41]
Meeting Nov 20th 2020 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #40 . 

Recording is [here](https://youtu.be/oz5Ikf_bxdw).

On the call: @mattodd @danaklug @edwintse @drc007 @MFernflower 

1. **Screening**.
a) _New compound suggestions_: New compounds were proposed last time (#38). There are no changes of strategy since last meeting. Main branch: exploration of the _para_-methyl substituted compound that was active, being explored by @danaklug and @edwintse. Suzuki reactions done by Ed, purifying.

Ongoing: playing with the imidazole and pyridine heteroatoms, re the possibility of the chelation mechanism by the bidentate ligand. e.g. thiazole bioisostere replacement of pyridine. Proposed pyrrole compound would be N-H donor, not chelator, which would be interesting.

@edwintse to keep an eye on synthetic accessibility/SM's.

@mattodd reminded people to keep an eye on lit searches in case of any scaffold hops as we change things more.

@loriferrins has suggested compounds she can contribute [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/38#issuecomment-724845443): N-alkylated compounds. 7-sub'd core seems to be more toxic to human cells (less toxic with 6-sub'd <-- observation by NEU @loriferrins) **Action** on @loriferrins to ship to UCL.

Q: @drc007 suggested related compounds may have already been made by DNDi - @danaklug to reach out to @bendndi
Discussion to continue on #35.

@loriferrins also has other data (e.g. tox) on these cores, and is actively exploring them, so we can exchange structures.

b) _Human Cytotox_: Ongoing.

2. **Synthetic Chemistry Update** by @edwintse. See below for slide.

3. **in vitro PK**: 
a) Residual uncertainty about the units between original data and those from Monash. Comparable? Check inherited data to be sure. **Action**: Mat. Resolved - see below.
b) **Benzofuran compound (821)** will be evaluated for metabolic ID by Hypha (paperwork pending).

4. **Community updates**
a) _Videos_: One-minute video update using the Tha/Dana protocol (OpenSourceMalaria/TechOps#3) has been done! **Action** on @danaklug to add captions and then post, then see how well it functions on social media. @mattodd's view is that the videos should focus on short, specific things, but this video is an excellent start. 

b) _Newsletters_. Another one needed, on Series 1 this time. People need to give their consent to be emailed, and we need a record of that. **Action** on @danaklug  to set up Google Form for sign-up, to solve GDPR issue. Done: [Dana has set up a Google form to sign up](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/40#issuecomment-726819446). Unsubscribe needed. Can this be done on a Google form? Link at the bottom of each newsletter to allow that, or rather reply to the email that the newsletter comes from. @danaklug to add text saying that we won't share emails, and to copy over existing emails to the associated sheet (which now becomes the master).

5. **Molecule contributions**
@drc007 suggested we try to crowdsource physical compounds - how? Twitter? Email? Newsletter? Would be helpful create landing page for molecule contributions (likely through GitHub). @danaklug has created a submission template now available at #39. @drc007 says what if we get the same compound from two people. Answer: handled as batches. The OSA compound sheet has internal codes, which ties batches to people (this is important). Provenance is important and should be in the master list. If people submit through @danaklug 's form, then we will have copies of those submissions. @drc007 can people check if compounds have been submitted? The compounds submitted through the form -> a sheet. No: the submission is currently an Excel sheet, so not linked. Instead we could create a Google form that would then install the submissions in a sheet, which people can then search. Need a simple way to submit the compounds using a form, then agreeing to terms. @danaklug will look into this (**ACTION**). Can we do batch uploads on a Google form, e.g. with Lori compounds? An incoming sheet can be easily checked and searched, and codes assigned during staging post.

**Discussion in meeting**: SGC site has [terms for molecules to be requested](https://www.sgc-unc.org/request-idg-tools) _from us._ This can happen (and we can take those terms). More likely is that molecules will be sent in. Important terms for donated molecules will include: 
i) If OSA is sent a sample, is OSA allowed to do something else with it? We need that the donation would be for anything OSA-related, but not beyond OSA. Allows cross-screening.
ii) Can we make derivatives? Yes, we need that permission.
iii) Indemnity. The molecule is contributed without necessarily an understanding of other properties, e.g. tox. Or that the molecule is infringing third party IP. i.e. donation is a washing-hands deal.
iv) Molecule contributions are openly associated with the contributor as the point of origin, i.e. attribution is given.

**Action** on @mattodd to draft text.

@drc007 said he was happy to reach out to people in his professional network to see if any related compounds are held and may be donated (**Action**) Chris needs the terms of donations first (above).

@mattodd mentioned the value of having a Twitter Bot that takes a molecule from the OSA spreadsheet and tweets out the structure with the strings and with a page where it is clear what the use of the molecule is. This allows for human to spot the molecules that OSA requires.

@mattodd also reminded people to keep an ongoing eye on sites such as Enamine, Manifold and Mcule, to check whether any molecules might be **commercially available**. We should always try to make the challenging molecules in the lab, and buy the others. This was addressed in the meeting with searches done by @MFernflower. Can get quotes for a number of relevant structures. Link to this installed on wiki.

AOB:

6. **Mechanism of action**: Experiments ongoing (see #30); update received, results expected soon.

7. **Biofunctionalisation**: **Action** Contract signed for further interactions with Hypha. Mat to arrange shipping with @danaklug and @edwintse 

8. **Series Origin/Similarity Landscape**: Mat is awaiting clearance for the GSK conversation and will report back when that's received.

9. **ELN**. @danaklug or @edwintse to try again (**Action**) Labarchives' molecule sketching facility to see if the ELN page is Google-able. i.e. sketch a molecule from OSA using the drawing facility, and check each day to see if it is indexed. ELN pages on which strings have been manually pasted are indexed (@mattodd checked this yesterday). Can we do away with manual strings pasting? Separately, @mattodd found that the OSA molecule spreadsheet is not indexed.

@drc007 said he would check this out (**Action**). He has submitted the sheet to Google. Follow-up to see if the molecules start to show up in Google searches.

Actions other than the chemical targets discussed (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Lori to ship some compounds to UCL for MRSA eval
- [ ]  ACTION ITEM: Lori to dig up relevant tox data on these compounds
- [ ]  ACTION ITEM: Mat to report back on Hypha.
- [ ]  ACTION ITEM: Mat to report back from GSK on what can be shared publicly about the series history.
- [x]  ACTION ITEM: Mat to resolve uncertainty in metabolic clearance units
- [ ]  ACTION ITEM: Dana or Ed to try out the Labarchives drawing facility.
- [ ]  ACTION ITEM: Chris to look into why the OSA molecule sheet is not Google-indexed.
- [ ]  ACTION ITEM: Mat to look into license terms for compound donation
- [ ]  ACTION ITEM: Chris to reach out to professional network for compound donations
- [x]  ACTION ITEM: This meeting video to be posted on YouTube.

**Comment by danaklug** [comment]
#39 has been updated with a draft Google form for compound submission. In order to upload files via Google forms, the submitter must have a Google account. The files will show up in my Google drive as I am the author of the form.

**Comment by mattodd** [comment]
OK, solution to the issue of apparently conflicting units:

RLM Clint units from Sue Charman's [data](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Metabolism/CDCO_UCL_Todd_20_001_Physchem%20and%20metabolism%20(3).pdf): 59 uL/min/mg (compound SB400868)

RLM Clint units from UNC [data](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Sources%20of%20Data/201905%20RLM%20SB400868.pdf): 142 mL/min/kg (compound SB400868)

These units are a factor of 10 out, with the expectation that the Monash number would be an order of magnitude smaller than the UNC number. We are not really seeing that difference for this compound for which we have both values, but it's the only value for which we have values from both labs, so difficult to conclude much. In future we expect to receive more data from Sue's lab, and I guess this is a reminder to be mindful of the units if we secure clearance data from other places, since it seems that there is not agreement on what the standard units should be.

**Comment by bendndi** [comment]
Not sure these are out by a factor of 10 (uL to mL is factor of 3, kg to mg is 1/3) so it all evens out, unless I'm missing something. 

For me these are relatively comparable data in that they are both "high clearance" (as opposed to moderate, or "very high"). The in vivo extrapolated CLint (mL/min/kg) is usually higher than the in vitro intrinsic Cl from which it is calculated (uL/min/mg.pr) -- just to give an example here are some values for some random compounds from an old series with in vitro CLint and extrapolated in vivo CLint _taken from the exact same experiment__ 

![image](https://user-images.githubusercontent.com/36627399/100093516-ed1c0100-2e57-11eb-95f0-e923c4d23f5a.png)

**Comment by mattodd** [comment]
@bendndi the volumes are 1,000x, the masses 10,000x (kg to mg, not g), so it's x10 out.

**Comment by danaklug** [comment]
Isn't it kg = mg * 1,000,000?

I think what I was missing is that it's an extrapolation calculation, not just a 1-to-1 unit conversion. Makes much more sense to me now. Thanks @bendndi!

**Comment by bendndi** [comment]
hmmm, I think we're both wrong here (mg to kg is 1,000,000).
Either way, it's not a direct conversion, the **in vitro** readout value, expressed as uL/min/mg.pr (i.e. mg of protein in the assay), is rate of clearance of a volume of solution over time by a known quantity of microsomes. If you know the mass of microsome used in the assay, and you know the scaling factors of the assay, this can be used to give you an **extrapolated in vivo**  vlaue, expressed as mg/min/kg where the kg is refering to per "kg of animal". Some labs report the in vitro, some report the in vivo, some report both. somemed chemists use the in vitro (e.g. me, AZ folks among others), whereas others will use the extrapolated in vivo, and others will use entirely different units / readouts like % remainig after 30 min, or Extraction ratio...

The key point is that the two values you have for SB400868 are roughly in line with each other based on

**Comment by bendndi** [comment]
@danaklug  you beat me to it on the mg to kg thing... Hope the above is helpful and convinces you there is not a discrepancy in rat microsomes across labs for your compound  :-)

**Comment by mattodd** [comment]
Whooooops, thanks. Open science = the chance to make simple arithmetical errors in public and irreversibly.
Massive thanks @bendndi for that great analysis - I'd not seen this before.

**Comment by danaklug** [comment]
Closing - links have been installed in the Project Meetings and Metabolic Clearance sections of the wiki.
