### ISSUE TITLE
Antibacterial Assay Dec 2020 (Results are in!)

### ISSUE THREAD

**Issue by edwintse** [opensourceantibiotics/Series-2-Diarylimidazoles#46]
The following 11 compounds (plus +ve and -ve controls) have been screened against MRSA and VRE by Paul Stapleton here at UCL. The MIC values (ug/mL) are shown below for each bacteria. Colour coding: 2 and 4 (green); 8 and 16 (orange); 32 and >32 (red).

![Assay compounds Dec 2020](https://user-images.githubusercontent.com/18062981/102070251-c453af80-3df6-11eb-8b94-3de9d10503b9.jpeg)
----

**Observations**

- The 5,6-core with the extra N atom (**863**) is inactive which is in agreement with the original data from @AlvaroLor 
- Adding and/or transposing N atoms on the bottom most ring (**873** and **874**) is not tolerated. It remains that we only get activity with a 2-pyridyl in this position.
- Out of the toluene isomers, 4-Me (**865**) is the best at 4 ug/mL with activity falling off with 3-Me (**976**), 2-Me (**977**) and removal of the methyl (**870**)
- Acetophenone (**973**) and dimethylacetamide (**974)** type substituents are not tolerated
- para-cyano (**975**) and para-chloro (875) are potent but are rather lipophilic (can we do para-fluoro? - MFernflower)
- The Cl-substituted DNDi core (**978**) is tolerated well (could we try and swap the Cl with hydroxyl or fluorine? - MFernflower)

--------

OSA_000XXX | SMILES
-- | --
863 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(N=CC=C5)=N2)=NC=CC=C1
873 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=NC=CN=C1
874 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=CN=CN=C1
875 | ClC(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
876 | ClC(C=C1)=C(Cl)C=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
973 | CC(C(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4)=O
974 | O=C(N(C)C)C(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
975 | N#CC(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
976 | CC1=CC=CC(C2=C(N=C3N2CCC3)C4=NC=CC=C4)=C1
977 | CC(C=CC=C1)=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
978 | ClC1=CC2=NC(C3=NC=CC=C3)=C(C4=CC=C(C)C=C4)N2C=C1
821 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=NC=CC=C1
820 | COC(C(OC)=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4

**Comment by MFernflower** [comment]
@edwintse Will this assay be MRSA only or will VREF also be included?

**Comment by MFernflower** [comment]
@edwintse I'm guessing results on monday?

**Comment by edwintse** [comment]
UPDATE: The original post has now been updated to include the potency results and some quick observations.

**Comment by danaklug** [comment]
The below is a schematic of a batchwise Topliss decision tree (more info [here](https://drug-hunter.com/2020/02/01/topliss/)).

![image](https://user-images.githubusercontent.com/53487492/102633917-b5cb0800-4116-11eb-8a5f-ddceccf29af0.png)

We've synthesized compounds **A**-**E** (below) and the order is **B**=**C**>**A**>**D**>**E**. While this doesn't exactly match any of the suggested rank orderings, it's closest to those in the orange box. Unfortunately most of the suggested molecules involve adding lipophilicity to the molecule, so we may want to consider whether we really want to pursue them (although the N,N-diethyl compound might be worth making).

![image](https://user-images.githubusercontent.com/53487492/102634147-0a6e8300-4117-11eb-82b0-c86891b8a762.png)

**Comment by drc007** [comment]
@danaklug Nice summary, and this is why I was suggesting the nitrile is perhaps the most interesting molecule. Retains activity whilst reducing lipophilicity.

**Comment by MFernflower** [comment]
The needed boronic acid for that is sold by SA

https://www.sigmaaldrich.com/catalog/product/aldrich/741809

@drc007

**Comment by MFernflower** [comment]
The needed boronic acid for that is sold by SA

https://www.sigmaaldrich.com/catalog/product/aldrich/741809

@danaklug @edwintse

**Comment by MFernflower** [comment]
@drc007 The needed boronic acid is cheap so a para amino on the topmost ring is also doable:

http://www.fluorochem.co.uk/Products/Search?searchType=C&searchText=%20214360-73-3

**Comment by MFernflower** [comment]
https://www.sigmaaldrich.com/catalog/product/aldrich/741809
http://www.fluorochem.co.uk/Products/Search?searchType=C&searchText=%20214360-73-3

Precursors for the para amino type compounds

**Comment by danaklug** [comment]
Closing - these compounds have been added to the SAR wiki.
