### ISSUE TITLE
Compounds from Lori Ferrins (Results!)

### ISSUE THREAD

**Issue by edwintse** [opensourceantibiotics/Series-2-Diarylimidazoles#48]
The following 6 compounds have just been received from @loriferrins. They will be sent for potency evaluation in early 2021.

![NEU Compounds](https://user-images.githubusercontent.com/18062981/102488901-a4292800-4064-11eb-8bc1-0607801b529a.jpeg)

**Comment by MFernflower** [comment]
Is NEU-6675 the known SKS compound you can get from sigma? @drc007

**Comment by lferrins** [comment]
@MFernflower it is similar but there are some key differences. Here is the link to the compound you are referring to: https://www.sigmaaldrich.com/catalog/product/sigma/s0193?lang=en&region=US

**Comment by MFernflower** [comment]
Thank you for clearing that up for me!

**Comment by MFernflower** [comment]
Cross ref to #53  @mattodd 

Hopefully we can get these molecules screened soon

**Comment by danaklug** [comment]
FYI: These compounds have been added to the [master sheet](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit#gid=1078638615) and have been given OSA IDs.

**Comment by danaklug** [comment]
Compounds have been dropped off with Paul. Results will be posted in a new Issue.

**Comment by MFernflower** [comment]
@danaklug @mattodd these results should be quite telling

waiting with bated breath

**Comment by danaklug** [comment]
Results are in!

![image](https://user-images.githubusercontent.com/53487492/108502815-4d7ddb80-72ab-11eb-874c-268364d4addf.png)

**Comment by danaklug** [comment]
Closing - these compounds have been added to the SAR wiki.
