### ISSUE TITLE
OSA Meeting Friday December 18th 2020

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#49]
Meeting Dec 18th 2020 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #47.

Recording is [here](https://youtu.be/va_5waLqUiQ).

On the call: @mattodd 

1. **Screening**
a) _Potency_
New results: #46. 
Conclusions (some already listed by @edwintse in #46):
. Controls were re-tested and agreed with previous. 
. Position of N on southwest ring varied. Potency lost. Just 2-N is not enough (e.g. compound 873). Note that the 3- and 4-pyridyls were tried previously and found to be not potent (821 vs 861, 862, 869).
. Alternative core in 978 possessed activity, implying that can be explored
. High sensitivity of para substitution in northwest aromatic ring. Cyano active (quite polar).
. 875 and 876 made as part of Topliss analysis. @danaklug to post what that tells us about next steps.
. Nevertheless: potency is hitting a wall. Need to break through to find more potent compounds.
. @loriferrins suggested replacing the cyano in 975 with amine (i.e. aniline).
. @danaklug already making OMe replacement of Cl in 978. Possible others, e.g. through direct displacement. e.g. pyrrolidine N through Buchwald Hartwig. Need to create stock of an intermediate that would allow access to multiple structures <-- sensible idea.
. @loriferrins asked about 5-membered ring replacements of 2-pyridyl. Some have been tried and came up as inactives (e.g. 866) but many (all?) have an amino substituent in the northwest. Maybe need one with other northwest substitution to better compare the impact. @loriferrins suggested compound 851 with para-F rather than ortho-F as a possible target. Also in the exploration of 5-membered rings as replacements of pyridine, all of the 5-membered rings had additional heteroatoms, e.g. the thiazole 843 (could try oxazole, but v similar to 843, but in any case S more like C in pyridine, so a nicely analogous compound).  @Giada-chem suggested 7-membered or other bigger subst. Perhaps substituted pyridyl, or isoquinoline or naphthyl in place of pyridine.
. Possibly pyrrolidine as saturated substituent to replace the 2-pyridyl, linked by the carbon? Synthetically difficult.  
. @loriferrins has put a CH2 between pyridyl and core imidazole (actually pyrazole). Used one-pot procedure, which is interesting. Not useful for saturated pendants in place of the pyridine, but still potentially interesting.
. @danaklug to order starting materials for one-pot synthesis attempts in January. Dana to post on the synthetic approach and available materials. @loriferrins has sent procedures and Dana will post those to Github. Potentially replace pyridine with saturated rings, though that is hard? @drc007 suggested quaternizing (MeI) the pyridine N then reducing (e.g. on 875), to access saturated ring analogs; this is possible, the middle (competing) ring being more hindered.
. In terms of decent amounts of stock, @edwintse did a gram-scale prep of 821 (for the hypha work) and got 560 mg out (50% each time) - total of 800mg in stock, can be used for exploratory synthesis.
. @MFernflower suggested reducing (hydrog) the eastern ring in des-chloro 978, again to de-aromatise. That core was made by @AlvaroLor compound 818, but it had the inactive northwest dioxo substituent. Hence possible to make 818 with para-tolyl, but it was suggested there would be metabolic issues with that compound and that such a change would increase lipophilicity.
. @drc007 suggested replacing the central core ring with a 2-arylbenzimidazole. This might again allow divergent synthesis of a number of compounds. Simplify the chem if active!
. @loriferrins suggested pyrazolo[1,5-a]pyridine core.
. Generally looking at core changes that might be synthetically available is good in order to consider bold changes to alter bioactivity.
. @edwintse found 2-pyridylbenzimidazole available at Fluorochem, and will search on others.

b) _Human Cytotox_
Underway in the lab of Andreas Schatzlein. This is also to test the metal-binding potential of the 2-pyridyl system. Updates will be at issue #3 .
@loriferrins has shared tox data on several related compounds: location?

2. **Synthetic Chemistry**
Not much but @edwintse did do a scale-up of OSA821 with a 50% yield.

3. **_in vitro_ PK**
Benzofuran compound (821) being evaluated for metabolic ID by Hypha.

4. **Community updates**
a) Newsletters. Action on @mattodd to write the second.
There is a Google form for sign-up [here](https://docs.google.com/forms/d/e/1FAIpQLSf4UieL5pRQqN5rOL4q-t57qcpJhHG_jqMXV774FPUJBmnBbQ/viewform?usp=sf_link). Link to be added to OSA GH landing page.... and elsewhere? Action on @danaklug , also to copy over existing newsletter recipient names to the sheet.

5. **Molecule contributions**

@loriferrins has shipped compounds #48. Received and fridged for evaluation in early 2021. They include derivatives with N-alkyl substitution in the northwest position (NEU-6729 vs NEU-6675 which has the N-H).

Crowdsourcing of physical compounds. @danaklug to look at landing page for molecule contributions: template now available at #39. Google form link also at #39 and [here](https://docs.google.com/forms/d/e/1FAIpQLSfiAgyVV_KMVflZoXvulEPHYio7wAgUeiTBqrA9iUMz9EKlNQ/viewform?usp=sf_link). 

Donation terms are at #45. @drc007 has reached out to people in his professional network to see if these terms are OK. Good comments back, some discussion in meeting needed. Terms need to be included on donations page. **Action** on @danaklug 

Terms updated in January by @mattodd at and this needs to be updated in the donations page.

6. **Mechanism of Action**
Results received via email and have been shared [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/tree/master/Mechanism%20of%20Action/2020%20Initial%20UNC%20Data/MRSA%20Project)
Discussion at #15. Action on @edwintse to ensure the data are also installed on Labarchives and linked to Github, to ensure we don't lose such crucial files.
Action on @mattodd to organise consultation on meaning of results.

7. **Series Origin/Similarity Landscape**
GSK conversation [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/4#issuecomment-743169238). **Action** on @mattodd to incorporate in wiki as needed.

8. **ELN**
@danaklug or @edwintse to try again (**Action**) Labarchives' molecule sketching facility to see if the ELN page is Google-able. i.e. sketch a molecule from OSA using the drawing facility, and check each day to see if it is indexed. ELN pages on which strings have been manually pasted are indexed (@mattodd checked this). Can we do away with manual strings pasting? Separately, @mattodd found that the OSA molecule spreadsheet is not indexed. @drc007 said he would check this out (**Action**).

AOB
- @mattodd mentioned the value of having a Twitter Bot that takes a molecule from the OSA spreadsheet and tweets out the structure with the strings and with a page where it is clear what the use of the molecule is. This allows for human to spot the molecules that OSA requires. **Action** on @mattodd to outline what this would entail

- (ongoing -> install in wiki as a way of working) @mattodd also reminded people to keep an eye on sites such as Enamine, Manifold and Mcule, to check whether any molecules might be commercially available. We should always try to make the challenging molecules in the lab, and buy the others. Action on @edwintse to include this in wiki somewhere logical.

(- @MFernflower moving towards becoming a pharmacy tech!)

Happy New Year...

**Actions** (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Mat to write second newsletter.
- [x]  ACTION ITEM: Dana to link newsletter signup somewhere central and copy over existing people.
- [x]  ACTION ITEM: Dana to make compound donations page/link obvious, and include terms on that page.
- [ ]  ACTION ITEM: Mat to organise session to discuss meaning of MoA data
- [ ]  ACTION ITEM: Mat to incorporate GSK remarks in wiki
- [ ]  ACTION ITEM: Dana and Ed to look into whether manual strings are still needed in Labarchives, or whether molecule sketching facility is sufficient.
- [ ]  ACTION ITEM: Mat to outline value of Twitterbot for molecule alerts.
- [ ]  ACTION ITEM: Ed to outline on wiki how we should keep in mind searches for commercially-available molecules from various suppliers, in parallel to the in-house synthetic chemistry.
- [ ]  ACTION ITEM: Chris to look into why the OSA molecule sheet is not Google-indexed.
- [x]  ACTION ITEM: This meeting to be posted on YouTube.

**Comment by danaklug** [comment]
I've updated the [submissions page](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Submissions,-Resources,-and-Data) with the license terms and links to Google forms and donation spreadsheet. ..

I made a few edits to the terms in order to incorporate the feedback from @drc007 and our discussion last week (#45) - if @mattodd @loriferrins @drc007 would like to quickly review these that would be great.

**Comment by MFernflower** [comment]
@edwintse @danaklug @mattodd   For the sake of completion I drew out @drc007 's benzimidazole structure hop:

![ChrisSwain_benzimidazole](https://user-images.githubusercontent.com/3164942/102660712-7e298380-4149-11eb-99b1-48ec91fa7fbc.png)

**Comment by danaklug** [comment]
Closing - this issue has been linked in the Project Meetings wiki.
