### ISSUE TITLE
Characterisation of compounds 

### ISSUE THREAD

**Issue by fidiris** [opensourceantibiotics/Series-2-Diarylimidazoles#5]
I've started a [Google Doc](https://docs.google.com/document/d/1uZO1TvXbm3wdYuugnJp-YGM4ZkDjaTF-1izKUnvz4f4/edit?usp=sharing) and copied over the synthetic chemistry data we've inherited. If you contribute to the synthetic portion of the project, please add the synthetic procedures and relevant characterisation data (1H, 13C, MS etc) to the document directly. Please keep the formatting as it is for consistency (i.e. ACS style ChemDraw files saved as images and pasted in, scaled to 30%). 

Links to ELNs can be found [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Sources-of-Data).

**Comment by danaklug** [comment]
Closing - this info has been incorporated into the wiki under "Submissions and Sources of Data."
