### ISSUE TITLE
OSA Meeting Friday January 22nd 2021

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#52]
Meeting Jan 22nd 2021 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #51.

Recording is [here](https://youtu.be/CVi0pR69_B4).

On the call: 

1. **Screening**
a) _Potency_
New targets discussed in previous [two]( https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/49) [meetings]( https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/51) summarized in the image below.
![Ideas_12-18-20](https://user-images.githubusercontent.com/53487492/105374579-7c7e3000-5bcd-11eb-8c7c-a358136a44fe.png)

Next potency screen will include any of the above targets that have been successfully synthesized, along with NEU compounds from @loriferrins (#48).

b) _Human Cytotox_
Underway in the lab of Andreas Schatzlein. This is also to test the metal-binding potential of the 2-pyridyl system. Updates will be at issue #3 .

@loriferrins has shared tox data on several related compounds, located in the [Sample Contributions]( https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/tree/master/Sample%20Contributions) repository. **Action** on @danaklug to summarize and integrate into master OSA molecules spreadsheet.

2. **Synthetic Chemistry**
No updates this week. @danaklug back in lab early/mid-Feb. Synthetic protocols from @loriferrins for the one-pot procedure (outlined below) are [here]( https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Synthetic%20Chemistry/Imidazopyridine%20one-pot%20procedure.docx). As per @mfernflower’s suggestion, a Google doc [shopping list]( https://docs.google.com/document/d/1i1_RV_jMK8N-iAj9jXsUAJnXBOOnSZDJpfydNXP3g20/edit?usp=sharing) has been created. @danaklug to place orders by end of Jan.
 ![One_pot](https://user-images.githubusercontent.com/53487492/105374784-af282880-5bcd-11eb-85f2-8dab4ceb8ebd.png)

3. **_in vitro_ PK**
Hypha results are in at #50 and will be discussed there. No action currently needed.

4. **Community updates**
a) Newsletters. Action on @mattodd to write the second newsletter
There is a Google form for sign-up [here](https://docs.google.com/forms/d/e/1FAIpQLSf4UieL5pRQqN5rOL4q-t57qcpJhHG_jqMXV774FPUJBmnBbQ/viewform?usp=sf_link). Link has been added to OSA GH landing page. Action on @danaklug , also to copy over existing newsletter recipient names to the sheet.

5. **Molecule contributions**
Terms discussed in #45, with new revision (discussed more at mattodd/blog#1). Terms have been updated on OSA Series 2 wiki and on the Google form [here](https://docs.google.com/forms/d/e/1FAIpQLSfiAgyVV_KMVflZoXvulEPHYio7wAgUeiTBqrA9iUMz9EKlNQ/viewform?usp=sf_link). 

6. **Mechanism of Action**
Results received via email and have been shared [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/tree/master/Mechanism%20of%20Action/2020%20Initial%20UNC%20Data/MRSA%20Project)
Discussion at #15. Action on @edwintse to ensure the data are also installed on Labarchives and linked to Github, to ensure we don't lose such crucial files.
Action on @mattodd to organise consultation on meaning of results.

7. **Series Origin/Similarity Landscape**
GSK conversation [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/4#issuecomment-743169238). @mattodd has incorporated into wiki. 

8. **ELN**
@danaklug or @edwintse to try again (**Action**) Labarchives' molecule sketching facility to see if the ELN page is Google-able. i.e. sketch a molecule from OSA using the drawing facility, and check each day to see if it is indexed. ELN pages on which strings have been manually pasted are indexed (@mattodd checked this). Can we do away with manual strings pasting? Separately, @mattodd found that the OSA molecule spreadsheet is not indexed. @drc007 said he would check this out (**Action**).

AOB
- @mattodd mentioned the value of having a Twitter Bot that takes a molecule from the OSA spreadsheet and tweets out the structure with the strings and with a page where it is clear what the use of the molecule is. This allows for human to spot the molecules that OSA requires. **Action** on @mattodd to outline what this would entail. Done at mattodd/blog#2

- (ongoing -> install in wiki as a way of working) @mattodd also reminded people to keep an eye on sites such as Enamine, Manifold and Mcule, to check whether any molecules might be commercially available. We should always try to make the challenging molecules in the lab, and buy the others. Action on @edwintse to include this in wiki somewhere logical.

**Actions** (can be checked as complete after the meeting).

- [ ]  ACTION ITEM: Mat to write second newsletter.
- [x]  ACTION ITEM: Dana to assemble shopping list for immediate purchase for both new ideas (e.g. benzimidazole) and one-pot procedure from Lori.
- [ ]  ACTION ITEM: Dana and Ed to look into whether manual strings are still needed in Labarchives, or whether molecule sketching facility is sufficient.
- [ ]  ACTION ITEM: Ed to outline on wiki how we should keep in mind searches for commercially-available molecules from various suppliers, in parallel to the in-house synthetic chemistry.
- [ ]  ACTION ITEM: Chris to look into why the OSA molecule sheet is not Google-indexed.
- [ ]  ACTION ITEM: Dana to dig up and summarise Lori's tox/metabolic data on related compounds.
- [x]  ACTION ITEM: This meeting to be posted on YouTube.

**Comment by MFernflower** [comment]
@danaklug I hate being a nickpick but in the discussed compoounds graphic one of the compounds I proposed is missing: 

Smiles is `CC1=CC=C(SC2=C(N=C3CCCN23)C2=NC=CC=C2)C=C1`

**Comment by mattodd** [comment]
You mean this? I'd not picked up on that in the notes, but fine. The RHS ring's obvs less important than the N -> S change or the nature of the para substituent.
![Screen Shot 2021-01-22 at 1 28 35 PM](https://user-images.githubusercontent.com/4386101/105496730-c93d3600-5cb5-11eb-84b8-2defde388164.png)

**Comment by MFernflower** [comment]
@mattodd @danaklug That is the missing compound 

We should be able to use the same arylation protocol for that and Chris Swain's structure hop

NaH in THF 0 °C-rt for 5 h - some papers reccomend adding Tetrabutylammonium iodide for really fussy substrates ( e.g https://www.organic-chemistry.org/abstracts/lit1/961.shtm )

**Comment by MFernflower** [comment]
@mattodd reason P-methyl was chosen is cause fluorochem.co.uk sells para-thiocresol in 50 gram bottles for 20 quid

**Comment by danaklug** [comment]
Closing - link to this issue has been added to the Project Meetings wiki.
