### ISSUE TITLE
OSA Meeting Friday January 29th 2021

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#53]
Meeting Jan 29th 2021 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #52.

Recording is [here](https://youtu.be/kcfHwfKGJso).

On the call: @mattodd @drc007 @danaklug @Giada-chem @MFernflower 

1. **Screening**
a) _Potency_
A summary of new targets discussed for the next round of may be found [here]( https://user-images.githubusercontent.com/53487492/105374579-7c7e3000-5bcd-11eb-8c7c-a358136a44fe.png). The next potency screen will include any of the above targets that have been successfully synthesized, along with NEU compounds from @loriferrins (#48).

b) _Human Cytotox_
Underway in the lab of Andreas Schatzlein. This is also to test the metal-binding potential of the 2-pyridyl system. Updates will be at issue #3 .

@loriferrins has shared tox data on several related compounds, located in the [Sample Contributions]( https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/tree/master/Sample%20Contributions) repository. **Action** on @danaklug to summarize and integrate into master OSA molecules spreadsheet.

2. **Synthetic Chemistry**
The Google doc [shopping list]( https://docs.google.com/document/d/1i1_RV_jMK8N-iAj9jXsUAJnXBOOnSZDJpfydNXP3g20/edit?usp=sharing) has been updated - Sheet now includes if compounds have been received by laboratory or not. 

Synthetic routes to proposed compounds are outlined below:

![Jan_2021_Synthesis](https://user-images.githubusercontent.com/53487492/106196623-43b6fb80-6177-11eb-8ffe-b752f0947f2d.png)

3. **_in vitro_ PK**
Hypha results are in at #50 and will be discussed there. No action currently needed.

4. **Community updates**
a) Newsletters. Action on @mattodd to write the second newsletter
There is a Google form for sign-up [here](https://docs.google.com/forms/d/e/1FAIpQLSf4UieL5pRQqN5rOL4q-t57qcpJhHG_jqMXV774FPUJBmnBbQ/viewform?usp=sf_link). Link has been added to OSA GH landing page. 

5. **Molecule contributions**
Terms discussed in #45, with new revision (discussed more at mattodd/blog#1). Terms have been updated on OSA Series 2 wiki and on the Google form [here](https://docs.google.com/forms/d/e/1FAIpQLSfiAgyVV_KMVflZoXvulEPHYio7wAgUeiTBqrA9iUMz9EKlNQ/viewform?usp=sf_link). 

6. **Mechanism of Action**
Results received via email and have been shared [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/tree/master/Mechanism%20of%20Action/2020%20Initial%20UNC%20Data/MRSA%20Project). Action on @edwintse to ensure the data are also installed on Labarchives and linked to Github, to ensure we don't lose such crucial files.

The initial discussion of results may be found at #15. Below are additional points raised in our meeting last week with Lee.

_Experimental design_
Lee was able to clarify some of the finer points of the experimental design: 

- The inhibitor bead cocktail consists of reversible but promiscuous (mammalian) ATP-site binders in order to capture as much of the kinome as possible. However, beads oftentimes bind other proteins that are not kinases. The [data]( https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Mechanism%20of%20Action/2020%20Initial%20UNC%20Data/MRSA%20Project/PC781_Wilson_MIBs.xlsx) that we have was not filtered and contains ALL proteins identified, not just kinases. This was the first time they'd applied this technique to a microbial system.

- The structures of inhibitors have been [published](doi.org/10.18632/oncotarget.24337) and are shown below.

![MIB_compounds](https://user-images.githubusercontent.com/53487492/106196766-74973080-6177-11eb-9350-a80ecd0a40ae.png)

- The targets in our dataset were identified by mass spec using a MRSA-specific database and are known MRSA proteins. 

_Results_
- Lee did not identify any of the targets on our [short list]( https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/15#issuecomment-758961676) as typical false positives for the assay and said they were fairly unique.

- The magnitude of the fold-change values is fairly typical for this experiment.

- Several of our targets of interest showed a positive fold change. Lee postulated this could be because a) proteins that are competed off of the beads due to treatment free up sites on beads for other proteins to bind; or b) the compound is binding to an allosteric site that increases protein’s affinity for the beads. Lee mentioned that he has seen this before with metabolic enzymes and leans toward this explanation. Upregulation is probably not the explanation because of short incubation time and use of lysate (as opposed to live cells).

- We should focus on targets with a negative fold-change first.

_Next steps_
- More literature searching on targets of interest. What is their role in MRSA biology? Are they essential for cell survival? Are any already known antimicrobial targets? @drc007 suggested cross-referencing Uniprot with ChEMBL.
- Repeat experiment. From Lee’s follow-up email: “Karim said he felt that we could have captured more proteins if he had started with more protein.  He was concerned that the lysis was incomplete.  I suggest that we repeat the experiment for that reason.” 
- The experiment could potentially be repeated with live cells, not lysate.
- Lee and co. can also do a total proteomics experiment, which would be a more unbiased approach. (Uncharacterized proteins would not be captured.) This would capture how the proteome responds to treatment with active compound and has led into mechanistic insight for other projects. This approach uses live cells in place of lysate.
- If antibodies are available to the target of interest, a Western blot competition assay would be useful.
- Pull-down/click chemistry assay with functionalized active compound. Potentially time-consuming to work out where to install the fuctionalization withough losing activity, although this experiment would be useful if the target is not captured by MIB experiments.

7. **Series Origin/Similarity Landscape**
GSK conversation [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/4#issuecomment-743169238). @mattodd has incorporated into wiki. 

8. **ELN**
@danaklug or @edwintse to try again (**Action**) Labarchives' molecule sketching facility to see if the ELN page is Google-able. i.e. sketch a molecule from OSA using the drawing facility, and check each day to see if it is indexed. ELN pages on which strings have been manually pasted are indexed (@mattodd checked this). Can we do away with manual strings pasting? Separately, @mattodd found that the OSA molecule spreadsheet is not indexed. @drc007 said he would check this out (**Action**).

AOB
- @mattodd mentioned the value of having a Twitter Bot that takes a molecule from the OSA spreadsheet and tweets out the structure with the strings and with a page where it is clear what the use of the molecule is. This allows for human to spot the molecules that OSA requires. **Action** on @mattodd to outline what this would entail. Done at mattodd/blog#2

- (ongoing -> install in wiki as a way of working) @mattodd also reminded people to keep an eye on sites such as Enamine, Manifold and Mcule, to check whether any molecules might be commercially available. We should always try to make the challenging molecules in the lab, and buy the others. Action on @edwintse to include this in wiki somewhere logical.

**Actions**
- [ ]  ACTION ITEM: Mat to write second newsletter.
- [ ]  ACTION ITEM: Dana and Ed to look into whether manual strings are still needed in Labarchives, or whether molecule sketching facility is sufficient.
- [x]  ACTION ITEM: Mat to follow up with Paul Stapleton to see if Lori's compounds can be screened in early February. 
- [ ]  ACTION ITEM: Ed to outline on wiki how we should keep in mind searches for commercially-available molecules from various suppliers, in parallel to the in-house synthetic chemistry.
- [ ]  ACTION ITEM: Chris to look into why the OSA molecule sheet is not Google-indexed.
- [x]  ACTION ITEM: Dana to dig up and summarise Lori's tox/metabolic data on related compounds.
- [x]  ACTION ITEM: This meeting to be posted on YouTube.

**Comment by MFernflower** [comment]
@danaklug @mattodd  Should Lori's compounds be send out for antibacterial assay now - I.E have a batch assay that is just those compounds and nothing else?

or do you want to wait untill you make and purify some of the compounds on the list above? 

Is it logistically possible for Lori's compounds be dropped off tomorrow fpr the MRSA and VRE screen?

**Comment by MFernflower** [comment]
@mattodd to follow up with Paul to see if Lori's compounds can be screened in an expedited fashion

**Comment by MFernflower** [comment]
@danaklug May want to add cas no  106-45-6 to the shopping list 

Para-thiocresol

As this compound should be also accessible from Ullmann reaction:



![2-{3- (4-methylphenyl)sulfanyl imidazo 1,2-a pyridin-2-yl}pyridine](https://user-images.githubusercontent.com/3164942/106317583-81ca2300-623c-11eb-89ee-b60c3513bfa0.png)

**Comment by danaklug** [comment]
The NEU tox data has been added to the [master sheet](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit#gid=2078630269) and summarized at #3.

**Comment by danaklug** [comment]
Closing - link to this issue has been added to the Project Meetings wiki.
