### ISSUE TITLE
MSSA Results

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#55]
We asked Paul to evaluate a few compounds for MSSA activity to assess whether our compounds were being effluxed (discussed [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/54#issuecomment-774115622)). Results below.

![image](https://user-images.githubusercontent.com/53487492/108505723-bebf8d80-72af-11eb-94b0-89577453fd3c.png)

From Paul: "It doesn’t look like efflux can explain the lack of increase in the activities of your compounds, so there must be another reason. Please note that a two-fold difference in MIC value is not considered significant (unless the difference can be demonstrated on multiple repeats)."

**Comment by MFernflower** [comment]
https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Efflux-pumps-and-AMR

results installed in wiki @mattodd
