### ISSUE TITLE
Resynthesis of OSA_000822

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#6]
We at UCL have ordered the necessary starting materials to resynthesize **OSA_000822** (the most active focused array compound) on scale according to the [original synthetic route](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Synthetic-Chemistry). This will provide material to use as a positive control in activity assays, as well as material for further studies.

**Comment by rhanson1046** [comment]
I am in quarantine but will do lit searches to see what structural variants may contribute to metabolic stability (related to the hotspots). Matt did you post the challenge yet with references yet? Judging from what I have seen so far TGFbetaR1 targeted compounds may overlap with the SB and ALM compounds and provide a source of compounds.

**Comment by danaklug** [comment]
We have resynthesized a stock of **OSA_000822** and confirmed its activity in the UCL MRSA assay. This issue will be closed.
