### ISSUE TITLE
DNDi Testing (Tox + Leish/Chagas/Sleeping Sickness) - RESULTS ARE IN!

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#60]
@loriferrins has gotten in touch with DNDi and they have agreed to test some of our compounds in their assays, including the MRC5 and PMM tox assays, as well as _L. donovani_ and _T. cruzi_ assays. 

Below are the structures of compounds that look like we would have enough material for testing. I've highlighted the ones that were evaluated in the first round of tox assays at UCL (in green) as well as those with MIC <8 (blue). Any others from this list that would be particularly interesting, either for toxicity or Chagas/Leish assays?

![DNDi_testing](https://user-images.githubusercontent.com/53487492/111350850-757a1800-867a-11eb-8470-be50c3b80bbe.jpg)

**Comment by MFernflower** [comment]
@danaklug @loriferrins @mattodd @bendndi **how high throughput is this screen?**

i.e could we ship all the compounds above to DNDI?

**Comment by bendndi** [comment]
@MFernflower It's high throughput, depending on where we ship the compound (the lab at Institut Pasteur Korea can handle 1000's componud / month; the lab at LMPH in Antwerp can handle ~100 / week.). LMPH would be the best destination for these, turnaround is about 5 weeks to n=1 and 6 weeks to n=2 data.
I've not been in the discussion with Lori about this but I don't think there should be a problem to ship all of them. Let me check but assume that if you don't hear back you can ship all.

**Comment by MFernflower** [comment]
@bendndi @mattodd @danaklug We will need to discuss this at upcoming meeting - hopefully all will be able to be shipped - would be cool if our ABX had some anti-protozoa activity

**Comment by MFernflower** [comment]
@danaklug @loriferrins @mattodd @bendndi  This will be discussed in tomorrows meeting hopefully

**Comment by lferrins** [comment]
Yep, we can test all of these with DNDi. @danaklug I will send you a spreadsheet so that I can generate DNDi numbers for these compounds for you.

**Comment by MFernflower** [comment]
This is fantastic news!!!

**Comment by danaklug** [comment]
I've just shipped the below compounds to @lferrins for Leish/Chagas testing!


OSA_ID | SMILES
-- | --
OSA_000812 | C1(C2=C(C3=CC=C(OCO4)C4=C3)N5C(CCC5)=N2)=NC=CC=C1
OSA_000820 | COC(C(OC)=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
OSA_000822 | C1(C2=C(C3=CC=C(SC=C4)C4=C3)N5C(CCC5)=N2)=NC=CC=C1
OSA_000831 | C1(C2=C(C3=CC=C(SC4=C5C=CC=C4)C5=C3)N6C(CCC6)=N2)=NC=CC=C1
OSA_000833 | C1(C2=C(C3=CC=C(C=CC=N4)C4=C3)N5C(CCC5)=N2)=NC=CC=C1
OSA_000834 | C1(C2=C(C3=CC=C(SC=C4)C4=C3)N5C(CCC5)=N2)=CC=CC=C1
OSA_000836 | CC1=NC2=CC(C3=C(N=C4N3CCC4)C5=NC=CC=C5)=CC=C2S1
OSA_000837 | CS(C(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4)(=O)=O
OSA_000838 | CS(C(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4)=O
OSA_000861 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=CN=CC=C1
OSA_000862 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=CC=NC=C1
OSA_000864 | N#CC1=CC=CC(C2=C(N=C3N2CCC3)C4=NC=CC=C4)=C1
OSA_000865 | CC(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
OSA_000868 | FC(OC(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4)(F)F
OSA_000869 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=CC=CC=C1
OSA_000870 | C1(C2=C(C3=CC=CC=C3)N4C(CCC4)=N2)=NC=CC=C1
OSA_000871 | C1(C2=C(C3=CC=C(SC=C4)C4=C3)N5C(C=CC=C5)=N2)=NC=CC=C1
OSA_000874 | C1(C2=C(C3=CC=C(OC=C4)C4=C3)N5C(CCC5)=N2)=CN=CN=C1
OSA_000875 | ClC(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
OSA_000876 | ClC(C=C1)=C(Cl)C=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
OSA_000973 | CC(C(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4)=O
OSA_000974 | O=C(N(C)C)C(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
OSA_000975 | N#CC(C=C1)=CC=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
OSA_000976 | CC1=CC=CC(C2=C(N=C3N2CCC3)C4=NC=CC=C4)=C1
OSA_000977 | CC(C=CC=C1)=C1C2=C(N=C3N2CCC3)C4=NC=CC=C4
OSA_000978 | ClC1=CC2=NC(C3=NC=CC=C3)=C(C4=CC=C(C)C=C4)N2C=C1

**Comment by MFernflower** [comment]
That is the CSV table for the graphic above yeah? @danaklug

**Comment by danaklug** [comment]
Results summary below! 

![DNDi_Results_6-29-2021](https://user-images.githubusercontent.com/53487492/123816910-9eec4600-d8ef-11eb-8518-99aa455f4d9a.jpg)

The raw data has been [uploaded](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Cytotox/DNDi_Results_Jun2021.xls) and include IC90s and _T. b. rhodesiense_ data in addition to the results shown above.

**Comment by MFernflower** [comment]
Interesting how our two inactive controls (812 and 820) are potent against Leish and Chagas

**Comment by danaklug** [comment]
See below for a color-coded version of the results. Chagas and leish targets are taken from the cited _Nat. Rev. Drug Disc._ paper. The tox cutoffs are somewhat arbitrary, so I'm also working on calculating SI values for those compounds that have activity against Chagas/leish to get a more nuanced picture of the kinds of selectivity windows we're looking at.

![DNDi_Results_6-29-2021](https://user-images.githubusercontent.com/53487492/126636153-c7942db3-93de-429b-8db5-13cff5e55bbd.jpg)

**Comment by danaklug** [comment]
SI tables below. Most have SI <10 (red), indicating a very narrow window between anti-parasitic activity and mammalian toxicity.

![image](https://user-images.githubusercontent.com/53487492/126666680-247356bd-e384-46c7-aa6f-cfb558209001.png)

![image](https://user-images.githubusercontent.com/53487492/126666730-8c264655-cc4c-43ac-988b-69046e46bf91.png)

**Comment by MFernflower** [comment]
I'm not certain as to how useful having SI's before MOA - if we are indeed
a pan proteasome inhibitor as Flavio suggested - we basically have effects
against every type of cell!

**Comment by mattodd** [comment]
Huh - those SIs not looking too hot. Most are positive, at least ;)
@MFernflower - let's not jump to conclusions, but instead think about how we might gather the relevant data. We're asking Lee to take a look. We also could identify a lab that runs proteasome inhibition screens. Here's one

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7026131/

Any others?

**Comment by lferrins** [comment]
I think that the key point regarding the SIs here is that the _T cruzi_ and _L infantum_ assays are intracellular, so the SI is indicative of whether the compounds are toxic to the host cell and contributing to the observed potency of the compounds. In short, there is _a_ window, but not a big one! 

For our purposes, I think it is more interesting to look at the raw TC50 data against these cell lines and then to look at how these data points compare to the others that you have. There may be a path to engineer in selectivity and this may become apparent as we look at the data.

We are actually about to start a project with Cyclica to try and identify off-targets of compounds using machine learning. We could potentially look at including a couple of these structures in the data set and see if we learn anything? It might be interesting to compare the different scaffolds, for example?

**Comment by danielgedder** [comment]
Closing issue. Data added into wiki page [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Potency-Evaluation-Against-Other-Pathogens)
