### ISSUE TITLE
Compounds for N-alkylation

### ISSUE THREAD

**Issue by lferrins** [opensourceantibiotics/Series-2-Diarylimidazoles#63]
Hi all, we have (I believe) sufficient stock in hand to be able to alkylate the following compounds. It would be great to get your feedback on which of these to prioritize. As I mentioned in the meeting today, we could potentially ask an undergraduate student to make these over the summer, but due to density restrictions in the labs currently, I have no idea how many will be possible. If we could aim for a top 10 list that would be a great first pass, I think?
Thanks!
![OSA_Compounds_for_alkylation](https://user-images.githubusercontent.com/65637708/111800420-51991b00-88a2-11eb-8fc1-3e565120037c.png)

**Comment by lferrins** [comment]
@danaklug was asking about the prep for making these N-alkylated compounds: 

General Procedure D: (N- alkylation)
To a mixture of imidazopyridine derivative (1 eq.) and Cs2CO3 (1.2 eq.) in DMF (1.5 mL) was added the respective iodoalkane (1.5 eq.) at RT and the mixture was stirred for 12 hours. 

When you are using iodomethane you can get overalkylation so you have to be a little more careful with the equivalents (use 1) and we make a stock solution when doing several at a time. Shouldn't be an issue here as we are going to use the isobutyl, right?

**Comment by danaklug** [comment]
@lferrins Thanks! Yep, I think we are going to go with the isobutyl.

**Comment by danielgedder** [comment]
Closing issue. Compounds were synthesized.
