### ISSUE TITLE
2D diagrams in Discovery studio 2021

### ISSUE THREAD

**Issue by Giada-chem** [opensourceantibiotics/Series-2-Diarylimidazoles#64]
Can someone help me to rotate one of these diagrams 90° degrees in Discovery studio 2021?
I would like to see the molecules displayed in the same way. These are similar molecules within the same binding-site.
Thanks!

![github](https://user-images.githubusercontent.com/72795101/112005848-6e905100-8b23-11eb-80e5-7fd17d4ce711.PNG)

**Comment by mattodd** [comment]
I was wondering if @WieselHenson @dayang-us @holeung @lpravda or @MelchorSanchez might know how to do this? How to orient the 2D interaction maps so that you can more easily compare the molecules in the same orientation?

**Comment by drc007** [comment]
Have you contacted Biovia?

**Comment by lpravda** [comment]
Sorry, no experience with Discovery studio at all. If these are released PDB entries you can check those at pdbe.org pages (but the same orientation is not guaranteed all the time).

**Comment by WieselHenson** [comment]
Hi, sorry, that is the same issue I experienced previously, so, to solve that problem, you can draw the interaction scheme in ChemDraw (this is also a common method in some papers), also please refer to [issue 30 in Murligase project](https://github.com/opensourceantibiotics/murligase/issues/30) for some insights!

**Comment by danielgedder** [comment]
Closing issue. All relevant discussions have been held.
