### ISSUE TITLE
March-April 2021: Next steps

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#66]
Following discussion at [today's project meeting](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/65), here's the document of compounds I had planned to synthesize. Some of these have been done already; my top priorities now are the five-membered ring pyridine replacements (to see if we can get away from some of the toxicity we've been seeing) and the amine-containing northwest substituents (to see if we can introduce some polarity).

![Analogues_2021](https://user-images.githubusercontent.com/53487492/112652123-f7b9c780-8e44-11eb-9163-a6bd23a0413e.jpg)

**Comment by danaklug** [comment]
Following last week's meeting (#68), here's an updated version with chemsitry from @flavioemery and @loriferrins as well as the amides that @MFernflower found from enamine. The editable ChemDraw version has also been [uploaded](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Synthetic%20Chemistry/March_2021_Synthesis.zip)

![March_2021_Synthesis](https://user-images.githubusercontent.com/53487492/115249134-3c710f80-a120-11eb-948b-0009727473ac.png)

**Comment by MFernflower** [comment]
@danaklug or @edwintse  to order the two compounds from Enamine corporation as per last meeting

**Comment by MFernflower** [comment]
@danaklug looks but two compounds concern me:

![115250428-77277780-a121-11eb-819c-e65c3af7a829](https://user-images.githubusercontent.com/3164942/116834341-9bf10580-ab8b-11eb-9156-1be6b5a6ffe9.jpg)

**Comment by danaklug** [comment]
@MFernflower Yes, I see where you're coming from. The diethylamine I included because it was a suggested compound from the Topliss analysis I did [earlier](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/46#issuecomment-748174592). With the benzyl, I was just trying to see what we could get away with sterically at this position since the analogs we've made thus far have fairly small substituents here. 

In any case, the chemistry should be fairly straightfoward and these compounds will be Giada's only focus when she gets in the lab so she should be able to make all of them. Happy to deprioritize the benzyl compound to the bottom of the list though.

**Comment by MFernflower** [comment]
If time/reagents permits it would be interesting to stick an azetidine ring onto it

**Comment by MFernflower** [comment]
@danaklug Perhaps a better replacement for the benzyl that's large but likely less oily would be Azepane

It's also super cheap - 100 ml for sixteen quid!


![pane](https://user-images.githubusercontent.com/3164942/117082765-15663080-ad11-11eb-96ae-64a1803bc11e.png)

**Comment by MFernflower** [comment]
I ran the benzyl and azapane compounds through swissadme 

Azepane compound is a bit less oily and considering how cheap SM is (see post above!)

Do you agree on replacing benzyl compound with the azepane? @danaklug  @Giada-chem

**Comment by drc007** [comment]
@MFernflower @danaklug @Giada-chem My concern about the azepane is that it is a bit of an SAR dead-end. A simple piperidine would answer the same question and there are plenty of substituted piperidines available for further exploration. Benzyl is rather different in that it brings into play other possible interactions (pi-stacking) in addition there are plenty of options for further SAR exploration, replacing ring carbons with heteroatoms, substituents on the ring, it also has a free NH for further substitution.

**Comment by MFernflower** [comment]
I'm in general pretty weary of the very large substituents on that top
benzene ring

If we keep cranking up the size (eg from diethylamino to benzyl to azepane)
isn't the end product going to have solubility problems?


@drc007

**Comment by drc007** [comment]
@MFernflower depends on the substituents.....

**Comment by danaklug** [comment]
@drc007 I agree. My thought behind proposing these analogues was to build out a small, diverse(ish) library using amines we have available at UCL so that we could get a feel for the SAR with some larger substituents. I agree that clogP is always something we should keep an eye on, but in terms of MW we're still in the 300s - so my other thought was that we could potentially pick up new interactions and pick up some potency by expanding out in space.

So the idea is that these five are a first pass using available materials and if anything looks interesting, we can and should be more deliberate about design going forward.

**Comment by MFernflower** [comment]
@danaklug @drc007  Very interesting discussion - it calls up the question of how large should an antibiotic be?

**I think the compounds that Giada and Ruben are going to make while a bit too oily for my liking are a good first pass** 

If something potent comes out of this i have several other ideas RE that subseries..

See you all tomorrow!!

**Comment by flavioemery** [comment]
Started the synthesis of the homologous series! Sharing data soon!

**Comment by danielgedder** [comment]
Closing issue. New discussions about the progress of the project can be found here #104 and #112
