### ISSUE TITLE
Amide linkers 

### ISSUE THREAD

**Issue by MFernflower** [opensourceantibiotics/Series-2-Diarylimidazoles#67]
After getting a manifold account I was able to do some searching of commercial databases and it turns out finding compounds with the pyridine is somewhat difficult. 

However - I was able to find the two amides that were mentioned in last meeting: - #65 

https://chem-space.com/CSMS00329477986-CEDBF4
https://chem-space.com/CSMS00425993179-A84DFC

**Comment by MFernflower** [comment]
@danaklug @mattodd to make final decision on purchase of these molecules.

@flavioemery perhaps could draw up a synthetic route / could perhaps take on synthesis of one of these molecules if resources permit

**Comment by MFernflower** [comment]
@loriferrins do you have a synthesis route for the amides?

**Comment by flavioemery** [comment]
@MFernflower I will work on it. Haven't done before, maybe @loriferrins has...anyway will send ideas later in this issue.

**Comment by lferrins** [comment]
Here is a general scheme that we used. There are likely other routes to obtain the free amine, but this worked in pretty good yields. The conditions for the amide coupling were: HATU (1.1 eq.), carboxylic acid derivative (1.0 eq.), amine derivative (1.0 eq.), DIEA (3 eq) in DMF (1.5 mL) at RT overnight. The reaction was quenched with water and after 10h in the fridge the ppt obtained was collected and dried to give the desidered compound. 

![S02_amide](https://user-images.githubusercontent.com/65637708/113298119-79887580-92c9-11eb-942f-9810419afd2e.png)

**Comment by flavioemery** [comment]
> Here is a general scheme that we used. There are likely other routes to obtain the free amine, but this worked in pretty good yields. The conditions for the amide coupling were: HATU (1.1 eq.), carboxylic acid derivative (1.0 eq.), amine derivative (1.0 eq.), DIEA (3 eq) in DMF (1.5 mL) at RT overnight. The reaction was quenched with water and after 10h in the fridge the ppt obtained was collected and dried to give the desidered compound.
> 
> ![S02_amide](https://user-images.githubusercontent.com/65637708/113298119-79887580-92c9-11eb-942f-9810419afd2e.png)

**Comment by flavioemery** [comment]
@MFernflower @lferrins route looks great to me.

**Comment by MFernflower** [comment]
Keeping this open untill the next meeting and then we will all discuss

**Comment by MFernflower** [comment]
@mattodd or @danaklug to place order when time permits

**Comment by MFernflower** [comment]
@danaklug @edwintse have compounds been ordered?

**Comment by danaklug** [comment]
> After getting a manifold account I was able to do some searching of commercial databases and it turns out finding compounds with the pyridine is somewhat difficult.
> 
> However - I was able to find the two amides that were mentioned in last meeting: - #65
> 
> https://chem-space.com/CSMS00329477986-CEDBF4
> https://chem-space.com/CSMS00425993179-A84DFC

Just got an update on these: Order was placed 21 May, lead time quoted as 20-30 days.

**Comment by MFernflower** [comment]
@danaklug Any updates on these two compounds that were commercially ordered?

**Comment by danielgedder** [comment]
Closing issue. Compounds were synthesized or purchased.  See OSA_1016 and 17.
