### ISSUE TITLE
OSA Meeting Friday May 21st 2021

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#72]
Meeting May 14th 2021 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #71. 

Recording is [here](https://youtu.be/-kYlgZGMRCg).

On the call: @mattodd @danaklug @edwintse, Dr Alex Vaideanu, @Giada-chem, @flavioemery, Dr Jyoti Chauhan (NEU), @MFernflower 

1. **Screening**

a) _Potency_
- Screening to be arranged for the new compounds from @loriferrins #62 and compounds from @edwintse (6 benzimidazoles) and @danaklug (5 compounds). @mattodd to ask Paul Stapleton for an assay slot. The benzimidazoles could go into the DNDi assay, which would be great! @edwintse tasked with liaising with @loriferrins to set this up if the structures are non-duplicative (@bendndi?).

- @loriferrins and team are soon to start the N-alkylation in #68 with Jyoti Chauhan (NEU, postdoc) and Bruno Quiroga (NEU, undergrad) <-- could these aspiring young scientists get Github accounts?

- Commercial amides found by @MFernflower. Need to order. Based on compound codes (e.g. Z1360007692, Z1360010544 <-- 10 mg each) they're available via make-on-demand??? <-- @danaklug could just try and order, see whether that works? @loriferrins has some amides, but with the methoxy of death™ 

b) _Parallel DNDI assay_
Compounds have arrived in DNDI lab - hopefully results in 4 weeks or so....

c) _Human Cytotox_
Brief update on toxicity of compounds OSA979-984 was given by Alex.
COADD originally use resazurin. Alex has checked with MTT, getting comparable results (including with the control used, tamoxifen).
There is tox observed for all compounds, pretty much. This disagrees with the low tox seen for compound OSA983 [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/3#issuecomment-771043105), but of course that assay is different.
It might be interesting to try to establish why tox is happening, to learn more about potential MOA.

@mattodd to reach out to COADD to ask which tox they tend to use for antibacterial.
Alex will complete the table she presented, to obtain publishable data set.

2. **Synthetic Chemistry**
Updates?

Targets are still as per #66.

3. **_in vitro_ PK**
Hypha production of the major metabolite: @edwintse has been purifying. The desired peak is close to another. Crude NMR of metabolite - All Ar peaks same, splitting of methylenes, so likely mono-OH on the saturated part of 5+5 core. Potentially at site predicted at https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/wiki/Metabolic-Clearance-Data.

If we get decent amount of OH product could try oxidizing to the ketone? - MFernflower

4. **Community updates**
a) Newsletters. Third newsletter needs to be written by @mattodd. Focus on S2

5. **Mechanism of Action**
Waiting on toxicity studies of OSA983 before contacting Lee Graves and team.

6. **ELN**
@danaklug or @edwintse to try again (**Action**) Labarchives' molecule sketching facility to see if the ELN page is Google-able. i.e. sketch a molecule from OSA using the drawing facility, and check each day to see if it is indexed. ELN pages on which strings have been manually pasted are indexed (@mattodd checked this). Can we do away with manual strings pasting? Separately, @mattodd found that the OSA molecule spreadsheet is not indexed. @drc007 said he would check this out (**Action**). <-- @drc007 can we remove this, or are further actions needed?

Previous guest appearance by Isabelle Giraud who described, with @drc007, how to auto-import the OSA Master List into Datawarrior. Action: install on wiki a simple how-to for how to visualize OSA molecules, and filter to this series.

AOB

- Action on @edwintse to include searching using Manifold in wiki somewhere logical. @MFernflower has signed up and found the two amides.

- Any other places that @Giada-chem should be looking for clues as to MoA/target? 

**Actions**
- [ ] @mattodd to ask Paul Stapleton for an assay slot.  
- [ ] @edwintse to investigate usefulness of shipping benzimidazoles --> DNDi evaluation pipeline.
- [ ] @danaklug to look into whether manual strings are still needed in Labarchives, or whether molecule sketching facility is sufficient.
- [ ] @edwintse to install reference to e.g. Manifold (and other resources) on wiki.
- [x] Dana, Mat or Ed to order the two amides from Enamine corporation as mentioned in #66 
- [x] @edwintse to complete isolation + indentification of Hypha metabolite
- [ ] @drc007 to look into why the OSA molecule sheet is not Google-indexed.
- [ ] @mattodd to write and send next OSA-S2 newsletter
- [x] This meeting to be posted on YouTube.

**Comment by flavioemery** [comment]
Preliminary reactions...next step: alkylation. Planning to have 3-5 different compounds.
![imidazo](https://user-images.githubusercontent.com/80112736/119141136-48036f00-ba1b-11eb-84d1-3774dd519eea.jpeg)

**Comment by lferrins** [comment]
I've just been looking into the question around PK. We have PK on 3 compounds in this series and (ridiculously) the only one that showed adverse effects in the study was DNDI0003363575. The other two were well tolerated but we didn't see sufficient exposure to progress to the efficacy study. Let me know if additional information would be helpful!
![S02_PK](https://user-images.githubusercontent.com/65637708/119428698-64cdca00-bcdb-11eb-8f41-51ed9d3181ce.png)

**Comment by MFernflower** [comment]
@lferrins Perhaps the tox was from the fluoropyridine motif?

**Comment by bendndi** [comment]
@lferrins the adverse events in '5375 may be also linked to overall exposure, since 3575 had 30 fold higher AUC than 3576 ; it could also however have been linked to the ABT codosing used to boost exposure in the 5375 study.
Note that for DNDI0003371181 (with imidazo-4-yl group in 2 position of the core instead of 2-pyridyl) we saw both good exposure and no adverse events even on multi-day dosing at 50 mg/kg - of course that may not be active in this case.

Note also that it not necessarily cytotox read outs that are going to correlate to adverse events seen in vivo, particularly when the adverse events are acute.
