### ISSUE TITLE
New compounds from NU

### ISSUE THREAD

**Issue by lferrins** [opensourceantibiotics/Series-2-Diarylimidazoles#78]
Hi all, Quillon has been making compounds in support of our ongoing efforts and we have some surplus material that we could send your way if you are interested? The structures are below. My 2 cents on this is that, while we have declared the methoxy "death" we only have n=1 (or 2?) and I'm wondering if some of these will test that hypothesis out a bit more? Otherwise, I feel this is a good set! 
<img width="262" alt="S02" src="https://user-images.githubusercontent.com/65637708/123281692-e3cf4180-d4d7-11eb-9794-de5726ea5e98.png">

**Comment by MFernflower** [comment]
This is a nice set of compounds - We did indeed find that adding an EDG to the bicylic ring was a bad idea (so the methylsulfur compound should be inactive as a stone at-least in theory)  - however it seems adding one to the pyridine system is fine see issue #76 

I think it's probably best to leave the bicyclic system without extra substituents but if this batch of compounds does get made it would finalized the "dont put things on the bicyclic ring" part of the SAR


@lferrins

**Comment by lferrins** [comment]
Thanks @MFernflower - just to clarify though, these compounds have already been made and are available to ship. We are just trying to make sure that they all make _sense_ to ship!

**Comment by MFernflower** [comment]
Thoughts @mattodd @danaklug Maybe we can finalize this "dont put things on the bicyclic ring" rule

**Comment by MFernflower** [comment]
@lferrins How did the methoxy even wind up on the core anyway?

**Comment by lferrins** [comment]
@MFernflower we use a substituted aminopyridine which gives us the methoxy in the core. We have been looking at it for anti-Leish activity in our research efforts.

**Comment by danaklug** [comment]
These compounds have now been shipped and assigned OSA numbers (see below) and will be included in the next round of MRSA screening.

![image](https://user-images.githubusercontent.com/53487492/125806244-8c6acf7e-076e-4557-b03e-2c1837b060dc.png)

**Comment by danaklug** [comment]
Compounds have arrived at UCL, thanks @loriferrins @QSimpson

**Comment by danaklug** [comment]
Closing, these structures have been folded into #84.
