### ISSUE TITLE
ADME Data (June 2021)

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#80]
New ADME data has been [uploaded](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/blob/master/Metabolism/AZ_OSA__ADME_Jun_2021.csv) and added to the master sheet. Data with structures below: 

![ADME_Results_6-23-2021](https://user-images.githubusercontent.com/53487492/124913425-03da2700-dfe7-11eb-8f88-43ebf5196b6b.jpg)

**Comment by MFernflower** [comment]
@danaklug this mostly covers the gen 1 core (the 5+5 ring system) do we plan on getting ADME for the 5+6 gen 2 ring systems

**Comment by MFernflower** [comment]
@danaklug this mostly covers the gen 1 core (the 5+5 ring system) do we plan on getting ADME for the 5+6 gen 2 ring systems?

**Comment by danaklug** [comment]
LogD has been added - see above for amended diagram, and below for some of my observations based on these data.

- The saturated core leads to improved solubility (978 v 865), but can still be a problem for metabolism. 
- The sulfoxide, sulfone, and dimethylamide (838, 837, 974) have the lowest LogD and best overall ADME profile of all compounds tested (unfortunately, none are active).
- 865 looks the best to me in terms of a balance of good ADME and potency (868 looking okay as well). 
- 864 is interesting because we have a very similar compound (975, p-CN instead of m-CN) with MRSA MIC = 4. I would suggest 975 is a high priority for ADME assessment, as well as some other compounds with the 5+6 core.
