### ISSUE TITLE
OSA Meeting Friday July 16th 2021

### ISSUE THREAD

**Issue by edwintse** [opensourceantibiotics/Series-2-Diarylimidazoles#82]
**There was no meeting July 9th 2021**

Meeting July 16th 2021 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #81. 

Recording is [here](https://youtu.be/c3jA1K3du2g).

On the call: @mattodd @danaklug @edwintse @drc007 @MFernflower @Giada-chem , Alex Vaideanu (UCL), Lee Graves (UNC), Quillon Simpson (NEU).

1. **Screening**

a) _Potency_
- @danaklug has updated SAR tables in wiki. <-- @mattodd asks: how do we ensure that new data sits in a queue until folded in?
- Benzimidazoles going to DNDi? @edwintse <-- we didn't talk about this meeting!
- Quillon's compounds have arrived for screening!  #78. Will be evaluated in the next round.

b) _Parallel DNDI assay_
Results were posted in #60. @danaklug to colour-code. Interesting activity, but again tox is tracking with potency. The Northeastern team are interested in some of these compounds, and we could jointly pursue and share.

c) _Human Cytotox_
Alex V updated in meeting. Tox similar to last time. Alex is generating a complete set of data for the paper. We need the Excel sheet and the pic for the wiki.
Check on DNA binding: Alex will ask around in UCL to see if we can do a simple DNA interaction assay to establish if there is DNA binding.
Check on apoptosis: let's wait for data back from Lee Graves before we address this since it's quite a lot of work for Alex.

2. **Synthetic Chemistry**
Current targets were described in #79. They remain the same. Updates today:

- NEU compounds: Quillon presented an update (could Quillon upload slides, below, please?)
- @flavioemery "homology series". 
- @Giada-chem aromatic amines in the northwest position (She's gotten the first compound but it needs purification):
![MicrosoftTeams-image](https://user-images.githubusercontent.com/4386101/126083006-d8635baa-4595-4011-a18a-33732efe7f4f.png)
- @danaklug doing one-pots, with some difficult purifications. Quillon to send Dana thei Biotage purification protocol.

3. **_in vitro_ PK**
@edwintse has updated wiki with metabolite data.
The removal of the 5-membered ring in the east of the molecule where the metabolism is happening. @danaklug was making attempts at doing that chemistry in (_where are the structures shown?_).

New ADME data obtained and drawn in #80. @danaklug added in the logD data. There are some excellent numbers here, but for inactive compounds. Some of the solubilities are very high. How come? Some of the clearances of those highly soluble compounds are also excellent. It would be useful to have data not on the 5-5 ring but instead on the 5-6 ring (that lacks the known metabolic liability). @danaklug to approach @loriferrins about this possibility. See also discussion below.

It would also be useful to plot the data in Datawarrior as 3-axis comparison of MIC vs logD vs HLM to spot outliers.

4. **Community updates**
a) Newsletters. Third newsletter needs to be written by @mattodd. Focus on S2.

b) Can we start to make use of the Planetary Forge Twitter Bot? Described at mattodd/blog#2. Would need an extra column inserted into the [Master List](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit?usp=sharing). Two aspects of potential use: i) alert people to project needs, ii) alert people to molecules that have been made.

5. **Mechanism of Action**
@mattodd [has reached out to Lee Graves](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/74#issuecomment-859595840) to ask if MoA experiments can resume. Lee came to the meeting. Running a repeat of the MRSA experiment is possible, but sourcing MRSA lysate is difficult. Running the experiment in HEK cells is much easier, and might reveal a human target. There was discussion about whether we might be hitting a proteasome target. @flavioemery posted some relevant lit [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/15#issuecomment-881472509). Lee was going to check (with own team, and with Tim Willson and Carrow Wells) if he had enough of the compounds that were originally sent.

6. **ELN**
@danaklug or @edwintse to try again (**Action**) Labarchives' molecule sketching facility to see if the ELN page is Google-able. i.e. sketch a molecule from OSA using the drawing facility, and check each day to see if it is indexed. ELN pages on which strings have been manually pasted are indexed (@mattodd checked this). Can we do away with manual strings pasting? Separately, @mattodd found that the OSA molecule spreadsheet is not indexed. @drc007 said he would check this out (**Action**). <-- @drc007 can we remove this, or are further actions needed?

Previous guest appearance by Isabelle Giraud who described, with @drc007, how to auto-import the OSA Master List into Datawarrior. Action: install on wiki a simple how-to for how to visualize OSA molecules, and filter to this series.

AOB:

- Action on @edwintse to include searching using Manifold in wiki somewhere logical (tech-ops page). 

**Actions** 
- [ ] @danaklug to look into whether manual strings are still needed in Labarchives, or whether molecule sketching facility is sufficient.
- [ ] @edwintse to install reference to e.g. Manifold (and other resources) on wiki.
- [ ] @drc007 to look into why the OSA molecule sheet is not Google-indexed.
- [ ] @mattodd to write and send next OSA-S2 newsletter
- [ ] NEU student team get Github accounts
- [x] NEU team to ship compounds
- [ ] Jyoti to upload NEU synthesis slides.
- [ ] @flavioemery to upload the pic of synthetic route to this GHI
- [ ] NEU search to see whether @loriferrins NEU team have analogs of OSA1000 already, to explore that core a little more.
- [x] @danaklug to colour-code DNDi data in #60.
- [x] @danaklug to add in logD data in #80.
- [x] @danaklug to see whether ADME data might be obtained on the 5-6 system.
- [ ] Alex V to complete write-up of tox data.
- [ ] Alex V to ask about possibility of DNA interaction experiment.
- [x] This meeting to be posted on YouTube.

**Comment by MFernflower** [comment]
![7-cyano-2-(pyridin-2-yl)-3-(p-tolyl)imidazo 1,2-a pyridine](https://user-images.githubusercontent.com/3164942/126074903-8827068b-4189-4f9a-813a-2d9c8e1cf15e.png)

One of the possible compounds that could be made to hopefully improve solubility

**Comment by lferrins** [comment]
I am not sure what your strategy is to improve solubility with this analog @MFernflower, can you expand? You could imagine something like this where the ortho-methyl may help to break up the crystal packing, you could also extend, or add bulkier groups if successful. ![image](https://user-images.githubusercontent.com/65637708/126080638-c00edd58-c89d-42dd-9032-43d4e4e259b5.png) 
Typically to improve solubility you would try adding groups like this, introducing ionizable groups, increasing sp3 carbon content or making a salt of the final compound.

**Comment by MFernflower** [comment]
The idea was to add a bit of polarity onto the core but I think your dimethyl idea is worthy aswell @danaklug Is the boronic acid for it available?

**Comment by MFernflower** [comment]
@loriferrins @danaklug @edwintse  The boronate for the dimethylphenyl is cheap:

![image](https://user-images.githubusercontent.com/3164942/126081246-88f4fe70-b095-4535-ab6c-28ab0b3f12ca.png)

**Comment by mattodd** [comment]
So I think the line of reasoning in the meeting was thus:

The ADME data in #80 shows that the "hypha" metabolic liability (on the saturated 5-membered ring) is not in and of itself a route to bad clearance: see compound OSA974, for example.

The data also suggest that the tolyl is not a major liability, necessarily. Replacing CH3 (in e.g. OSA865) with OCF3 (OSA868) doesn't help. (It's possible that in this case oxidation on the 5-membered ring is dominating).

The data do instead suggest that highly soluble compounds are cleared slowly. This is a known effect, since cyp enzymes tend to exist in hydrophobic environments. OSA974, OSA837, OSA838 all have high solubility and low clearance. All have logD around 1, yet are not potent.

So can we maintain the motifs associated with potency while introducing a group that brings predicted logD close to 1. It appears that we might be able to introduce groups onto the 6-ring, but these would need to be quite polar.

<img width="344" alt="Screenshot 2021-07-18 at 22 00 12" src="https://user-images.githubusercontent.com/4386101/126081970-1308298b-9262-47c8-b33d-591534a49ace.png">

Sulfoxide? CH2NH2? Piperazine? @drc007 's [page](https://www.cambridgemedchemconsulting.com/resources/physiochem/logD.html) is useful here.

**Comment by MFernflower** [comment]
@mattodd Lori's crystal breaking idea is quite interesting but it would likely make metabolism worse

**Comment by MFernflower** [comment]
@mattodd 7-amino on the core seems like a promising lead but no idea how stable it would be  - should be able to make it by reacting the above bromo compound with aqueous ammonia but who knows! 
![image](https://user-images.githubusercontent.com/3164942/126247329-a9e49d78-b9a7-4c94-afcc-02f7fa97ec1f.png)

**Comment by QSimpson** [comment]
Hi all, I mentioned in the last meeting that we have a pretty expansive SPR for the series, particularly for un-alkylated compounds. I just want to caution that we have found there to be little correlation between lipophilicity and aq. solubility. We normally observe gains in solubility with the introduction of ionisable functionality or with interruption of crystal packing via increased 3-D character. Unfortunately for us, this results in loss parasite activity. The small caveat is for N-alkyl compounds; if the alkyl chain is small we observe improvement to solubility and potency.

Attached are three-variable plots for our entire data set for the series
[series 2 solubility vs lipophilicity.pdf](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/files/6857660/series.2.solubility.vs.lipophilicity.pdf)
[series 2 solubility vs lipophilicity-zoom.pdf](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/files/6857661/series.2.solubility.vs.lipophilicity-zoom.pdf)

**Comment by QSimpson** [comment]
@mattodd looking at the series as a whole we also don't observe a strong correlation between more soluble compounds having improved metabolic stability. This is for either Clint (rat hepatocytes) vs solubility _or_ Clint (Human Liver Microsomes) vs solubility. 

Again I've attached graphs of our data set that supports this statement.
[series.2.solubility.vs.lipophilicity.pdf](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/files/6857887/series.2.solubility.vs.lipophilicity.pdf)
[series.2.solubility.vs.lipophilicity-zoom.pdf](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/files/6857888/series.2.solubility.vs.lipophilicity-zoom.pdf)

**Comment by QSimpson** [comment]
Meeting slides July 6th
[OSA July 16th.pptx](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/files/6858874/OSA.July.16th.pptx)
