### ISSUE TITLE
OSA Meeting Friday July 23rd 2021

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#83]
Meeting July 23rd 2021 at 2pm UK time at https://ucl.zoom.us/j/92800004715. This page follows on from #82. 

Recording is [here](https://youtu.be/BaPVY4_M_r8).

On the call: @mattodd @edwintse @danaklug @QSimpson @drc007 

1. **Screening**

a) _Potency_
-  When new data come in, how do we ensure that new data sits in a queue until folded in?
- Benzimidazoles going to DNDi? Seems like yes! so action now on @edwintse or @danaklug to send to @loriferrins.
- Screening run slotted for early next week - this includes compounds from @QSimpson (#78 thanks!) and @Giada-chem (yay!) and new one-pots from @danaklug. Compounds from Flavio?

b) _Parallel DNDI assay_
Results were posted in #60. @danaklug has colour-coded the data and calculated SIs. Not amazing. Interesting activity, but again tox is tracking with potency. The Northeastern team are interested in/optimistic about some of these compounds, and we could jointly pursue and share. NEU usually aims for an SI of about 10 (which some of the compounds have, and so could be "green"). 865 vs 975: methyl to nitrile, but significant change in tox. So need more of a dive into tox/SAR data. *And* these are in vitro data. Some of the pathogen potencies are actually very good (sub micromolar). @QSimpson [shared slides with the structures they are interested in here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/82#issuecomment-884507480). 5-5 ring system better ADME properties, all other things being equal. Any actions here, other than sharing compounds?

@drc007 

c) _Human Cytotox_
- Alex V updated in the last meeting. Toxicity similar to previous screens Alex has done. Alex is generating a complete set of data for the paper. We need the Excel sheet and the pic for the wiki.
- Check on DNA binding: Alex will ask around in UCL to see if we can do a simple DNA interaction assay to establish if there is DNA binding.
- Check on apoptosis: let's wait for data back from Lee Graves before we address this since it's quite a lot of work for Alex.
- **Action** on @mattodd to look into submission to NCI 60 assay, as a clue to potential tox/mech of tox. 

2. **Synthetic Chemistry**
Current targets were described in #79. They remain the same. Updates today:

- A screening run is slated for early nextweek
- @flavioemery "homology series" - Waiting on updates
- @Giada-chem aromatic amines in the northwest position. First compound obtained pure, working on second.
- @danaklug doing one-pots, with some difficult purification work. @QSimpson is in contact about purification and things seem better.

3. **_in vitro_ PK**
The Hypha data suggested the saturated 5-membered ring was a liability. Could be removed. @danaklug was making attempts at doing that chemistry in <-- where are the structures shown?

New ADME data in #80. There are some excellent numbers here, but for inactive compounds. Some of the solubilities are very high. How come? Some of the clearances of those highly soluble compounds are also excellent. It would be useful to have data not on the 5-5 ring but instead on the 5-6 ring (that lacks the known metabolic liability). @danaklug to approach @loriferrins about this possibility. @mattodd posted the conclusions and synthetic plan [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/82#issuecomment-882116977).

It would be useful to plot the data in Datawarrior as 3-axis comparison of MIC vs logD vs HLM to spot outliers. Any volunteers?

4. **Community updates**
a) Newsletters. Third newsletter needs to be written by @mattodd. Focus on S2.

b) Can we start to make use of the Planetary Forge Twitter Bot? Described at mattodd/blog#2. Would need an extra column inserted into the [Master List](https://docs.google.com/spreadsheets/d/168-a1_l51Nfbms67eG8zU8p-EhEtEO26FUzRInbu7fY/edit?usp=sharing). Two aspects of potential use: i) alert people to project needs, ii) alert people to molecules that have been made. Could we tag them as different in this way?

5. **Mechanism of Action**
Lee Graves came to the last meeting. Running a repeat of the MRSA experiment is possible, but sourcing MRSA lysate is difficult. Running the experiment in human (HEK or perhaps HeLa) cells is much easier, and might reveal a human target. There was discussion about whether we might be hitting the proteasome organelle. @flavioemery posted some relevant lit [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/15#issuecomment-881472509). Lee was going to check (with own team, and with Tim Willson and Carrow Wells) if he had enough of the compounds that were originally sent. 

6. **ELN**
@danaklug or @edwintse to try again (**Action**) Labarchives' molecule sketching facility to see if the ELN page is Google-able. i.e. sketch a molecule from OSA using the drawing facility, and check each day to see if it is indexed. ELN pages on which strings have been manually pasted are indexed (@mattodd checked this). Can we do away with manual strings pasting? Separately, @mattodd found that the OSA molecule spreadsheet is not indexed. @drc007 said he would check this out (**Action**). <-- @drc007 can we remove this, or are further actions needed?

Previous guest appearance by Isabelle Giraud who described, with @drc007, how to auto-import the OSA Master List into Datawarrior. Action: install on wiki a simple how-to for how to visualize OSA molecules, and filter to this series.

AOB:

- Action on @edwintse to include searching using Manifold in wiki somewhere logical (tech-ops page). 

**Actions** 
- [ ] @danaklug to look into whether manual strings are still needed in Labarchives, or whether molecule sketching facility is sufficient.
- [ ] @edwintse to install reference to e.g. Manifold (and other resources) on wiki.
- [ ] @drc007 to look into why the OSA molecule sheet is not Google-indexed.
- [ ] @mattodd to write and send next OSA-S2 newsletter
- [ ] @flavioemery to upload the pic of synthetic route to this GHI
- [ ] NEU search to see whether @loriferrins NEU team have analogs of OSA1000 already, to explore that core a little more.
- [ ] @danaklug to colour-code DNDi data in #60.
- [ ] Alex V to complete write-up of tox data.
- [ ] Alex V to ask about possibility of DNA interaction experiment.
- [ ] This meeting to be posted on YouTube.

**Comment by drc007** [comment]
Assays for looking at permeability. Caco-2 used as a model of the intestinal epithelial barrier.  Or MDCK-hMDR1 canine kidney cells transfected with hMDR1 gene (transporter), also used as model of blood brain barrier because of high level PGP expression.
