### ISSUE TITLE
MRSA Evaluation July 2021 - Tentative Results

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#84]
The compounds below (the bulk of the lot being from @QSimpson #78 along with some molecules synthesized by @Giada-chem and myself) are scheduled to be dropped off for testing on Wednesday July 28th. Results will be posted here.

![MRSA_Eval_July2021](https://user-images.githubusercontent.com/53487492/126983464-0ebf4c95-3651-46fc-b40d-4cb22897a452.jpg)

**Comment by danaklug** [comment]
See below for results received from Paul this morning. I think it's likely that we will need to get these compounds rested against MRSA: all compounds, even positive control **OSA_822**, have MRSA MIC >32. I'll do some QC of the **OSA_822** sample as well to double check that it is still okay.

In the meantime, the MSSA results may suggest the general trends for this set since the activities against the two strains have generally been within 2-fold of each other for the series to date.

![MRSA_Eval_July2021](https://user-images.githubusercontent.com/53487492/127632103-2b5f2cd8-bef3-4245-b4b5-2fe9186e440f.jpg)

**Comment by mattodd** [comment]
Yes, that's funny. If the +ve control is looking fine, then I'll approach Paul again. Good spot on the correlation between the two (historically).

**Comment by danaklug** [comment]
I've run an LCMS and 1H NMR, both look fine. And it's performed as expected against MSSA.

**Comment by MFernflower** [comment]
Even though the results seem suspect it is interesting that 1004 has activity considering that our SAR has currently said that putting nothing on the 6 part of the core is optimal @danaklug

**Comment by mattodd** [comment]
Paul is happy to re-test, which will be in September (given the holiday season is upon us).

**Comment by MFernflower** [comment]
@edwintse has been making some new compounds - so perhaps we should run the re eval and the new compounds a the same time @mattodd so that would mean no meetings for the entire month of august and we reconvene first week of September?

**Comment by danaklug** [comment]
These compounds have been retested - updated results in #92.
