### ISSUE TITLE
[Moved to next week] OSA S2 Meeting: Friday, September 3rd 

### ISSUE THREAD

**Issue by MFernflower** [opensourceantibiotics/Series-2-Diarylimidazoles#88]
This meeting has been moved to next week

(see comment below)

**Comment by mattodd** [comment]
Let's postpone this meeting to the following week @MFernflower @danaklug @edwintse . Some people are still away or at conferences or have just come back from vacation. @drc007 @loriferrins @flavioemery @QSimpson @Giada-chem But everyone can check action items outstanding in #87
