### ISSUE TITLE
MRSA Evaluation September 2021 - RESULTS

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#92]
The new compounds below have been dropped off to Paul for MRSA evaluation. Results of both new compounds and retested ones from July (#84) will be posted here once they come in.

![image](https://user-images.githubusercontent.com/53487492/134185891-7c5340a9-1f98-4ae4-b586-adf6ef035630.png)

Positive control: **OSA_822**

Issue to be closed after: 
- [x] Raw data has been uploaded to lab notebook
- [x] Data has been added to the OSA master sheet
- [x] Data has been incorporated into SAR wiki

**Comment by danaklug** [comment]
Results are in! Unfortunately, they don't look amazing. However, the positive control has behaved as exepected and we have a few moderately active compounds in the set (Paul mentioned that based on this he suspects his previous MRSA batch was contaminated).

![MRSA_Eval_Sept2021](https://user-images.githubusercontent.com/53487492/134644613-a00270a2-f59f-4cfc-a5e7-f0bd51153734.jpg)

Issue to be closed after: 
- [ ] Raw data has been uploaded to lab notebook and GH repository
- [ ] Data has been added to the OSA master sheet
- [ ] Data has been incorporated into SAR wiki

**Comment by MFernflower** [comment]
@danaklug @mattodd @QSimpson A possible compound that could be made from the above results is this:

![image](https://user-images.githubusercontent.com/3164942/134711605-39c0a8d9-dd90-4915-93f9-b2e9262e6891.png)

**Comment by danaklug** [comment]
Compounds have been added to the SAR wiki.
