### ISSUE TITLE
Postponing Fri 24th Sept Meeting to Fri Oct 1st

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#93]
Hi all - I need to be at a teaching strategy awayday thing on Friday and there's an important session at 2pm London. I suggest we postpone till the following week if that's OK?

_Developments_:
1) A selection of new compounds are being screened against MRSA #92
2) Daniel's making compounds - it'd be very good to have an update next week @danielgedder ?
3) Alex is on vacation, but completing tox analysis. @danaklug please see if she can present on Oct 1st?
4) Lee Graves seeking MRSA lysate - @mattodd to chase.
5) @QSimpson could maybe update next time on the targets being assigned to the NEU undergrads?
6) Other actions in #89

**Comment by drc007** [comment]
Fine with me

Cheers

Chris
