### ISSUE TITLE
SAR Gaps

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#94]
I've been working on the SAR tables to update the wiki and to identify gaps in our analysis. The proposed tables are below but it would be great to get some feedback and discussion going.

Rows highlighted in green all represent the same compound which has matched pairs across multiple tables, and which we haven't yet made. Rows highlighted in yellow represent proposed compounds that fill in some of our gaps.

-------------------------------------------------------------------------------------------------------

We've done well making matched pairs for the northwest substituent and these proposed molecules primarily cover avenues that we haven't really explored, as opposed to filling any obvious holes.

![image](https://user-images.githubusercontent.com/53487492/135459103-af890fe7-f49d-461f-b6c5-b4bbf06862f0.png)

![image](https://user-images.githubusercontent.com/53487492/135459176-2115e516-01a6-4b2e-8e27-0aca8cabb6d9.png)

Likewise the SW position has been well-covered. Potentially some more exploration of substituted pyridines would be something  to consider.

![image](https://user-images.githubusercontent.com/53487492/135459970-7c710b6e-e7bc-4628-ae9e-6a623872bee1.png)

The core is the patchiest in terms of SAR analysis, and this is because the original set contained some matched-pair core compounds that are ultimately not useful for determining SAR because they all had an inactive substituent in the NW position. There are therefore a few compounds that could be made here to fill some gaps.

![image](https://user-images.githubusercontent.com/53487492/135459706-8b002a20-1721-4435-aa50-bdf4ef358645.png)

N-alkylation has been well-covered, but the direct attachment/NH/amide linker table needs to be filled in.

![image](https://user-images.githubusercontent.com/53487492/135460148-e1133f17-71f5-44da-878b-04b4a7bed777.png)

![image](https://user-images.githubusercontent.com/53487492/135460425-d304bb07-f367-48f5-b905-68c517586402.png)

Finally, these two groups contain some compounds which I've not really been able to fit into the previous analysis and may not be essential to consider when trying to analyze SAR but are included for the sake of completeness.

![image](https://user-images.githubusercontent.com/53487492/135460540-ad0be156-d0fb-4b46-8200-336488e7cf54.png)

And the below compounds are all inactive and don't match well to any others, also included for the sake of completeness.

![image](https://user-images.githubusercontent.com/53487492/135460617-a03ee70b-c3b2-4456-8ddd-bd01a067c5b9.png)

The below is a summary of proposed compounds for consideration: 

![SAR gaps](https://user-images.githubusercontent.com/53487492/135461806-73b0f717-9011-4512-84b7-073f7711ba83.jpg)

**Comment by mattodd** [comment]
Really excellent analysis, Dana, and perfect for today's discussion.

**Comment by QSimpson** [comment]
> @QSimpson You said in today's meeting you may have some compounds with a N,N-Disubstituted aliphatic head group but that they tend to fall apart in acidic conditions - when you have time could you check your stocks to see if anything fits?
> 
> ![image](https://user-images.githubusercontent.com/3164942/137566206-8691981e-bdf9-401e-a3d1-6d1bdbd8947a.png)

We haven't made any bis alkyl compounds, but have made several N-alkyl compounds. Typically the N-alkyl compounds are unstable to acidic conditions such as normal phase chromatography. @mattodd @danaklug we have the unsubstituted amine on-hand which could be bis-alkylated with the isobutyl group if that is of interest.

**Comment by QSimpson** [comment]
> @mattodd @danaklug There's another commercially available compound that could hypothetically fill a SAR gap:
> 
> https://mcule.com/MCULE-5022923774-0/
> 
> ![image](https://user-images.githubusercontent.com/3164942/137652811-dde63af1-817c-4b5b-9e62-a2a1c4ae12f5.png)

@MFernflower What SAR hole would this fill? OSA-988 is very similar to the compound you are suggesting here.

**Comment by danielgedder** [comment]
Closing issue! Some compounds suggested here were synthesized. Proposal and discussions of the synthesis of novel compounds are [here](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/104) and the follow-up is [here ](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/112).  Everyone is encouraged to look at the draft paper posted by @danaklug and contribute/comment and check if still any SAR gaps. https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/101
