### ISSUE TITLE
OSA Series 2 Meeting Nov 5th (No meeting Oct 22nd, 29th)

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#98]
Hi all. We are currently:

1) Awaiting arrival of compounds from @danielgedder and @QSimpson / @loriferrins - _thank you for arranging shipping_!
2) Awaiting the next potency eval from Paul Stapleton, which will take place on the 27th.
3) Looking forward to hearing from Alex V on the final tox analysis - hopefully can join on 29th.
4) Ditto from Lee Graves on the MoA experiments - hopefully can join on 29th.

Previous meeting recording is up at #96 for those of you who'd like to remind yourselves of where we are and the current actions. @danaklug is on vacation today, and I'm stretched at our usual meeting time, **so shall we postpone to next week when we'll likely have new data**? @flavioemery @drc007 @edwintse 

To consider:
1) any SAR holes? #94 
2) [which compounds to send for ADME](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/96#issuecomment-940979680), to help our publication?

**Comment by danielgedder** [comment]
Closing issue. The discussions were held here or initiated in other issues.

**Comment by mattodd** [comment]
Yes OK to close. I installed a mention of @drc007 's work on the "static compound list for Google indexing" in the wiki [here](https://opensourceantibiotics.github.io/murligase/CompChemTools/ForIndexing/OSA_data.html).
And on the mur ligase wiki [here](https://github.com/opensourceantibiotics/murligase/wiki/Sources-of-Data#master-molecules-spreadsheet) and on TechOps wiki [here](https://github.com/opensourceantibiotics/OSA_Tech_Ops/wiki/Molecule-Master-List). Important methodological point that would become less crucial were we to have access to an appropriate compound registration system.
