### ISSUE TITLE
MRSA Evaluation November 2021 - RESULTS

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#99]
All compounds have arrived and will be delivered to Paul on **Wednesday, Nov. 3**. Structures are shown below and results will be posted to this Issue.

![MRSA_Eval_Oct_2021](https://user-images.githubusercontent.com/53487492/139672388-bf2f3ef4-1697-4030-96fe-6542732686b8.jpg)

Positive control: **OSA_822**

Issue to be closed after: 
- [x] Raw data has been uploaded to lab notebook
- [x] Data has been added to the OSA master sheet
- [x] Data has been incorporated into SAR wiki

**Comment by danaklug** [comment]
Results of the latest MRSA screen below; some moderately active compounds, but again nothing below 4 ug/mL.

![MRSA_Eval_Oct_2021](https://user-images.githubusercontent.com/53487492/140420845-a4eb4200-7b17-46ad-8c77-b0f23b87daac.jpg)

Both positive controls performed as expected (**OSA_822** MRSA MIC = 2 ug/mL; vancomycin MRSA MIC = 0.12 ug/mL). Original data file may be found [here](https://au-mynotebook.labarchives.com/share/Dana%2520Klug/NDA2LjkwMDAwMDAwMDAwMDAzfDY5Njg2LzMxMy9UcmVlTm9kZS8yNzQ0OTY1MzExfDEwMzIuODk5OTk5OTk5OTk5OQ==).

**Comment by MFernflower** [comment]
Disappointing to see how many were not potent - maybe a compound like this could be worthwhile? 


![image](https://user-images.githubusercontent.com/3164942/140427273-bb20f046-ae6d-4f7a-8e03-07584808baf4.png)

**Comment by danaklug** [comment]
Compounds have been added to the SAR wiki.

**Comment by DataClassified391** [comment]
How do I receive Vancomycin syringes by mail today? My DNA was mutated by animals and need assistance on Billing?
Heather M Urich-Armani
Dr. Psychiatry Urich-Armani
